- .github/workflows/circuit.yml
- circuit/src/execution-delivery/src/lib.rs
- circuit/src/execution-delivery/src/tests.rs
In this PR I: 
- Implemented a function called `select_authority` which changed the method of selection from selecting the first authority to selecting the authority with a given escrow account
- Added tests
> Refactor authority selection - Closes #60

- .github/workflows/circuit.yml
- circuit/Cargo.lock
- circuit/src/chain_spec.rs
- circuit/src/contracts-registry/src/lib.rs
- circuit/src/execution-delivery/src/exec_composer/mod.rs
- circuit/src/execution-delivery/src/lib.rs
- circuit/src/primitives/Cargo.toml
- circuit/src/primitives/src/lib.rs
- circuit/src/runtime/src/lib.rs
- circuit/src/xdns/src/lib.rs
This PR implements *most* of the acceptance criteria for #65 . The complete implementation requires an additional PR to be made on the [parity-bridges-common](https://github.com/MaciejBaj/parity-bridges-common) repo ([found here](https://github.com/paritytech/parity-bridges-common/pull/1072)).
In this PR: 
* [pallet-xdns] Implemented `update_ttl` call and `best_available` function.
* Refactored `retrieve_gateway_pointer`. Moved to t3rn-primitives and now returns a vector of Gateway Pointers.
* Used `retrieve_gateway_pointer` function in `retrieve_gateway_protocol` so that it fetches gateway metadata and uses it to instantiate a Gateway Protocol.
* Refactored `XdnsRecordId` to ony use the 4-character gateway id instead of the whole XdnsRecord struct to make it queriable from external …
> Integrate Multi Finality Verifier with Xdns to provide fresh data about active Gateways - Closes #65

- gateway/pallet-escrow-gateway/runtime-gateway/Cargo.toml
- gateway/pallet-escrow-gateway/runtime-gateway/src/lib.rs
- gateway/pallet-escrow-gateway/runtime-gateway/src/tests.rs
Allows to invoke different scenarios based on provided arguments into separate methods: 
Introduce bit flags and modify the flow of execution based on them.
> Refactor exec composable at Gateway into separately-callable methods - Closes #64

- circuit/Cargo.lock
- circuit/pallets/execution-delivery/src/lib.rs
- circuit/primitives/Cargo.toml
- circuit/primitives/src/lib.rs
- circuit/primitives/src/side_effect.rs
- circuit/primitives/src/xtx.rs
Move structures out of ExecDelivery to primitives and introduce Confirmed Side Effect to Execution Delivery
Closes #164
> Move structures out of ExecDelivery to primitives - Closes #164

- circuit/primitives/src/event_signature.rs
- circuit/primitives/src/lib.rs
Implement and test events signature decoder - receives and event signature, like "Transfer(from,to,value)" and returns the tuple that contains decoded Event name: "Transfer" and its argument names: `vec!["from","to","value"]`.
Refers #119
> Implement decoder for events signature - Refers #119

- node/parachain/src/cli.rs
- node/parachain/src/command.rs
- node/standalone/src/cli.rs
For some reason the `circuit-collator key` subcommand got missing for our parachain node... 🗝️ back now
> Readd parachain node key cmd

- primitives/src/lib.rs
While working on the demo we were seeing `GatewayVendor=Ethereum` in Polkadot Apps UI even though in JS land we were using `GatewayVendor=Substrate`. This mini change should align GatewayVendor across the various sub projects and resolve any ambiguity.
> fix: align GatewayVendor enum layout across sub projects

- Cargo.lock
- gateway/pallets/runtime-gateway/src/lib.rs
- pallets/circuit-portal/src/mock.rs
- pallets/contracts-registry/Cargo.toml
- pallets/contracts-registry/src/lib.rs
- pallets/contracts-registry/src/tests.rs
- pallets/contracts-registry/src/types.rs
- primitives/Cargo.toml
- primitives/src/bridges/polkadot_core/mod.rs
- primitives/src/contracts_registry.rs
- primitives/src/lib.rs
- primitives/src/storage.rs
needed for https://github.com/t3rn/3vm/pull/25
Moves some types and a trait for the Contracts Registry into primitives, this is then injected by `pallet-wasm-contracts`
Fixes https://github.com/t3rn/x-t3rn/issues/172
> 3VM: load contracts and account data from Contracts Registry / Circuit

- Cargo.lock
- pallets/circuit-portal/src/lib.rs
- pallets/circuit/src/lib.rs
- pallets/circuit/src/tests.rs
- pallets/xdns/src/lib.rs
This is to support the removal of pallet ORML and Balances from t3rn protocol. 
Also, it loads the value type size allowing various gateway configs to be correctly validated.
> Support protocol updates removing pallet ORML and Balances dependencies 

- docker/devnet/docker-compose.yml
- docker/devnet/run.sh
Fixes a path typo that would prevent building the docker images from scratch. And removes unused code.
> fix: rm path typo 2 docker file

- node/parachain/src/chain_spec.rs
- node/parachain/src/command.rs
- runtime/parachain/src/lib.rs
- scripts/get-rococo-artifacts.sh
- scripts/run-rococo-collators.sh
Bundles a wild set of changes in preparation and required for launching on Rococo.
Once this is merged I will need to tag development, to have chain spec changes aligned with the prebuilt collator binaries we are running and the `polkadot-js/apps` config changes I been staging.
> Rococo launch preparation

- pallets/multi-finality-verifier/src/lib.rs
Fixes a bug in mfv regarding to gateway preregistration. The mfv pallet and any preregistered gateways are now unhalted right from initialization.
how mfv interaction it fails:
> fix: unhalt the pallet and any preregistered gateways

- Cargo.lock
- node/parachain/src/chain_spec.rs
- node/standalone/src/rpc.rs
- node/standalone/src/service.rs
- pallets/account-manager/Cargo.toml
- pallets/account-manager/src/lib.rs
- pallets/account-manager/src/transaction.rs
- pallets/circuit/src/lib.rs
- runtime/parachain/src/lib.rs
- runtime/standalone/src/lib.rs
These repatriates gas fees from contract authors.
It effectively adds a hook into pre_dispatch so that we can check for the call type, and if the call type is a call to the contracts pallet, we append the author data there.
Then it gets passed to the Unbalance handler in `account-manager` if the call has some beneficiary, and sends the adjusted gas fees to the beneficiary.
This should be super easy for `pallet-evm` when we do 3VM Level 3.
Due to the way that balances and `tx-payment` are designed, those traits are not in frame_support. So we need to have a macro which we define in `account-manager`, so that we don't copy-paste this. 
Also fixes some lints.
Writing tests is gonna be tricky, but let's see where we get!
> 3VM(account-manager): repatriate gas fees to contract authors

- client/types/package.json
Pins `@t3rn/types` package dependencies to avoid breakage and/or old/resolved errors from creeping back up.
> chore: pin types pkg deps

- .github/workflows/update_dev_docs.yml
Adds a github action for generating rustdocs on each development merge. The docs are then sent to atlas, where they are served from via nginx. Protocol is not included.
> Adds github action for generating and deploying rust docs

- .github/workflows/collation-check.yml
Adds a nightly (03:33am) pipeline to ensure circuit is collating.
> ci: Adds a nightly pipeline to ensure circuit is collating

- .github/workflows/collation-check.yml
Attempt to fix ENOENT 4 `pchain.Dockerfile` by pointing 2 up2date `development`.
> fix: collation check ci pipeline points to development explicitly

- .github/workflows/collation-check.yml
- docker/devnet/docker-compose.yml
Collation CI still [failing](https://github.com/t3rn/t3rn/runs/6640963777?check_suite_focus=true).
Adjust the Docker Compose file version and adds a prep step that rebuilds the Circuit image on top of the latest development.
> fix: adjust compose file version and run against latest circuit

- .github/workflows/collation-check.yml
- docker/devnet/README.md
- docker/devnet/docker-compose.yml
- docker/devnet/run.sh
Devnet ports were colliding with our collator ports...
> fix: untangle devnet and collator ports

- devnet/.gitignore
- devnet/README.md
- devnet/run.sh
Introduces a `#![no_docker]` devnet to simplify development 🐋🔫
```bash
./devnet/run.sh up   # 2 spinup
./devnet/run.sh down # 4 teardown
```
> fix: devnet is now #![no_docker]

- .github/workflows/collation-check.yml
Switches the collation check CI pipeline to the `#[no_docker]` devnet..
NOTE: #342 should be merged first 2 be secure
> chore: switch collation check 2 a nodocker devnet

- client/grandpa-ranger/justification-decoder/Cargo.toml
Reverts updates to `codec` and `scale-info` to allow justification decoding.
> fix: grandpa-ranger decoder deps

- .github/workflows/collation-check.yml
- devnet/run.sh
Installs `subkey` during `./devnet/run.sh up` if it is not present on the system. Should ultimately fix the collation check CI..
> fix: maybe install subkey while ./devnet/run.sh up

- pallets/account-manager/src/manager.rs
- runtime/parachain/src/accounts_config.rs
- runtime/standalone/src/accounts_config.rs
- types/src/side_effect.rs
Previously, we were able to use reserve_repatriating even if the account didnt exist. Now there are changes to pallet-balances we can't use that way.
Instead, we now slash_reserved to create an imbalance, then we deposit_creating with the imbalance.
Also has a minor change to the default split algo so the escrow account doesn't get dusted. In the future this will be replaced by some set of DustSafeAccounts like treasury etc.
> fix: the account manager is now in line with the changes to reserve_repatriating

- devnet/run.sh
- node/parachain/src/chain_spec.rs
Speeds up devnet runs by removing dangling XDNS preseeds for rococo-local.
Also, increases node startup timeouts to allow smooth runs on weak machines.
> Speed up devnet

- Cargo.lock
- scripts/upgrade-runtime.sh
We can now get the wasm and its hash for an authorize-enact style upgrade.
> Reenable runtime upgrades by replacing srtool with subwasm

- README.md
Adds a couple badges to the main README. On click each badge redirects to the respective target. The Discord invite link does never expire.
> docs: add github and social badges to readme

- client/executor/circuit/listener.ts
- client/executor/index.ts
The SideEffect naming has changed, this updates the executor accordingly
> fix: Correct received event names after new SFX are available for executors

- devnet/run.sh
Unpins `subkey` within `./devnet/run.sh` since the `2.0.1` version got purged.
Should also fix the collation pipeline.
Closes [#412](https://github.com/t3rn/t3rn/issues/412)
> Fix devnet by unpinning subkey

- scripts/run-rococo-collators.sh
Should enable sending metrics to the collective Substrate telemetry system.
Metrics include:
```
system.connected
system.interval
block.import
notify.finalized
afg.authority_set
```
Ultimately we just want our collators to show up here..
> chore: enable collator telemetry

- .dockerignore
- .github/workflows/circuit-collator-release.yml
- collator.Dockerfile
Reintroduces a collator release pipeline step that publishes a collator Docker image to the GitHub container registry. Additionally, the pipeline now triggers a continuous deployment pipeline in our chainops repo.
> Prepare continous collator deployments

- .dockerignore
- collator.Dockerfile
The docker image was missing `libssl` shared objects etc. so just runnning with a full blown ubuntu for now.
> Refactor the collator docker image to incl. all runtime deps

- .github/workflows/conventional_changelog.yml
- .github/workflows/lint_commits.yml
- .github/workflows/pr-alert.yml
Feat: Adds linting to commits, grouping them on release, and ensuring commit messages fit the conventional commits standard
Fix: Adds version number to the Pull Request alert GH Workflow step, as specific versioning is required
> Commit Linting during pipeline execution

- node/t0rn-parachain/src/chain_spec.rs
- node/t3rn-parachain/src/chain_spec.rs
- primitives/src/lib.rs
- primitives/src/monetary.rs
- runtime/mock/src/lib.rs
Bumps our mainnet collator candidacy bond from `0.016TRN` to `10000TRN`.
> Increase mainnet collator candidacy bond

- pallets/circuit/src/optimistic/mod.rs
- pallets/circuit/src/tests.rs
- primitives/src/side_effect/mod.rs
Only access reserved bond when other SFX exist when slashing
Fixes #497
> Only access reserved bond when other SFX exist when slashing

- pallets/circuit/src/escrow/mod.rs
- pallets/circuit/src/lib.rs
- pallets/circuit/src/state/mod.rs
- pallets/circuit/src/tests.rs
Total xtx rewards aren't used and the reward system relies solely on atomic rewards per SFX. 
Remove obsolete "total_rewards" field from Xtx
> Remove total Xtx rewards from Circuit 

- .github/workflows/circuit.yml
- .github/workflows/zombienet-test.yml
- Cargo.toml
- README.md
- node/README.md
- tests/zombienet/Makefile
This PR is changing how jobs are executed by our runners and how cache layer is used.
- ep1c worker reconfigured to use cache from memory
- new worker on AWS
- github actions caching removed from jobs to not slow down build process
- Makefile for zombienet test changed to separate `setup` and `test` stage
Those changes reduce time of:
- `lint` job from 7m to ~2m
- `build and test` job from 20m to 6:50
- `zombienet test` job from 30m to 28m (where blockchain tests take around 20m and can't be sped up)
> Github Actions using new runners

- .github/workflows/zombienet-test.yml
- tests/zombienet/Makefile
Changes to Makefile of zombienet
- setup step is required dependency step for tests
- bring back sccache commands to Makefile
> fix: Makefile setup step should be a dependency for tests

- .github/workflows/release-t0rn.yml
- tests/zombienet/Makefile
- tests/zombienet/download.sh
- tests/zombienet/download_latest_wasm_blob.sh
- tests/zombienet/download_previous_collator.sh
- tests/zombienet/increment.sh
- tests/zombienet/mainnet.toml
- tests/zombienet/smoke/0001-is_up_and_registered.feature
- tests/zombienet/smoke/9999-runtime_upgrade.feature
- tests/zombienet/smoke/runtime_upgrade.js
- tests/zombienet/zombienet-real-upgrade-sim.toml
- tests/zombienet/zombienet.toml
This uses predefined releases to test with, speeding up zombienet much more.
Also adds some better testability to the scripts for downloading.
Tested here https://github.com/t3rn/t3rn/actions/runs/4102683866/jobs/7076121595
> tests: retrofit zombienet to t0rn

- runtime/t0rn-parachain/src/parachain_config.rs
- runtime/t3rn-parachain/src/parachain_config.rs
reset scheduler::MaximumSchedulerWeight to 80% block weight to t0rn and t3rn runtime.
this is fix to current inability of releasing further runtime upgrades via pallet-scheduler
> fix: reset scheduler::MaximumSchedulerWeight to 80% block weight to t0rn and t3rn runtime 

- .github/workflows/circuit.yml
Disable pallet executors tests for now since they are causing a lot of OOM issues and kernel faults.
> ci: disable pallet-executors tests

- client/packages/executor/config/config.ts
- client/packages/executor/src/pricing/coingecko.ts
- client/packages/executor/src/pricing/index.ts
- client/packages/executor/tests/pricing.test.ts
Some tests were broken because the PriceEngine class could not stop fetching data.
Now, it's possible to disable it for testing and/or to set a custom frequency.
Addresses issue #746
> fix: add update frequency

- scripts/upgrade-runtime-set-code.sh
This changes to runtime upgrade script allows for increments of runtime versions higher than 1.
Such situation can occur when release with cargo release is made but runtime upgrade is not run.
> build: runtime upgrade script checkes runtime versions correctly

- .github/workflows/circuit.yml
- .github/workflows/dependabot-update.yml
- .github/workflows/release-t0rn.yml
- .github/workflows/release-t3rn.yml
- .github/workflows/runtime-upgrade-t0rn.yml
- .github/workflows/subalfred.yaml
- .github/workflows/update-dev-docs.yml
- .github/workflows/zombienet-test.yml
[GHA actions-rs/toolchain doesn't support rust-toolchain.toml](https://github.com/actions-rs/toolchain/issues/126)
Instead we can use `rustup show`, which does install correct toolchain.
[Explanation why `rustup show` does install correct toolchain](https://github.com/rust-lang/rustup/issues/2070#issuecomment-545096849)
> Basically whenever rustup tries to find a toolchain it has implicitly been told should exist, it will force an installation if it cannot find it. Thus cargo build will automatically install a toolchain where needed, etc. rustup show happens to need to find the active toolchain in order to print out its version information, hence it ends up installing it. It is intended behaviour, yes.
If …
> build: install rust toolchain defined in rust-toolchain.toml config [skip release]

- .github/workflows/circuit.yml
- .github/workflows/executor.yml
- .github/workflows/lint-commits.yml
- .github/workflows/runtime-upgrade-t0rn.yml
- .github/workflows/subalfred.yml
- .github/workflows/zombienet-test.yml
When github runner is fresh then circuit build or other action that uses paths-filter will fail due to not initilized git repo.
Additional remove of unnecesary use of GH_PAT and renaming subalfred action so we have consistent extension yml used.
> build: gha should checkout code before running paths-filter [skip-release]

- finality-verifiers/grandpa/src/lib.rs
- pallets/portal/src/lib.rs
By default, extrinsics are not transactional, meaning state writes that occur before an error are not reverted. This introduced some hidden bugs in grandpa FV and portal. To ensure this doesn't happen in the future, we should always test errors with ´assert_noop!´ instead of `assert_err!`.
- updated tests in grandpa to use `assert_noop`
- fixed failing test by making extrinsic transactional
- make register gateway in portal transactional
> fix: make extrinsics transactional

- Cargo.lock
- pallets/3vm/Cargo.toml
- pallets/3vm/src/lib.rs
- pallets/3vm/src/mock.rs
- pallets/3vm/src/precompile.rs
- pallets/contracts/src/tests/threevm/mock.rs
- pallets/evm/precompile/portal/Cargo.toml
- pallets/evm/precompile/portal/src/lib.rs
- pallets/evm/precompile/util/Cargo.toml
- pallets/evm/precompile/util/src/lib.rs
- pallets/evm/src/lib.rs
- pallets/evm/src/tests/threevm/mock.rs
- pallets/portal/src/lib.rs
- primitives/Cargo.toml
- primitives/src/lib.rs
- primitives/src/portal.rs
- primitives/src/threevm.rs
- runtime/mock/src/contracts_config.rs
- runtime/standalone/src/contracts_config.rs
- runtime/t0rn-parachain/src/contracts_config.rs
- types/abi/src/recode.rs
Moves the portal precompiles into 3vm
This refactors the precompile to use pre-defined indexes from primitives. Moves a lot of the responsibility for making the precompile arguments into the module itself and moves the tests too.
Unfortunately, due to an oversight in RLP, I have disabled most 3vm calls coming from precompiles since they never actually worked. I need to make a ticket for us to RLP-recode every call through ABI, much like the same way we do with this portal module.
Adds some logging to portal.
Allows extracting the callee from the precompile. NOTE: We currently manually use the 12-byte appendix since it isn't smart to reinject the …
> feat: move portal precompiles to 3vm

- .github/workflows/release-lock.yml
- .github/workflows/runtime-upgrade-t0rn.yml
This is dummy GHA that waits for release concurrency to finish
Reason behind it is that after release is finished, we want to commit cargo release changes and changelog
So anything in merge queue needs to wait for release to finish
Release Notes:
- Chore: Minor changes to GitHub Actions workflows for improved readability and documentation.
> "A few small tweaks, a little bit of care,
> Our GitHub Actions now have flair!
> With comments and descriptions, clear as can be,
> Our code is now more readable, you'll see!"
> ci(gha): wait for release to finish before merge [skip release]

- runtime/standalone/src/system_config.rs
- runtime/t0rn-parachain/src/system_config.rs
Release Notes:
- New Feature: Added support for `Attesters` calls in two `Contains<Call>` implementations.
This change may impact the behavior of the code and should be reviewed thoroughly to ensure that it doesn't introduce any bugs or security vulnerabilities.
> "With Attesters now in play,
> Our system's stronger every day.
> Bugs and flaws we'll keep at bay,
> Thanks to this PR, hip hip hooray!"
> feat: allow attester calls

- .github/workflows/test-circuit.yml
Rationale: zombienet is always run before runtime upgrade so any additional run on development is superfluous.
This will lower the pressure on our github runners
Release Notes:
- CI pipeline logic modified to run smoke test job only if changes are made to the source code and branch is not development.
- Superfluous test step removed from CI pipeline.
🎉 "Changes made with care, 
CI pipeline now aware. 
Smoke tests run with precision, 
Code quality on a mission." 🎉
> ci(gha): run zombienet test only before runtime upgrade

- .github/workflows/test-e2e.yml
Chore: Modify e2e test workflow to run only when "e2e" label is present in the pull request. 
> "E2E tests now run with ease, 
> Only when the label's there to please."
> ci(e2e): tests should not run when label e2e is not added atm

- .github/workflows/update-dev-docs.yml
- client docs deployed in one step to save time
- steps are run on self hosted runners
Release Notes:
- Documentation: Modified deployment process of client documentation and added self-hosted runners. Changes include modifying the `runs-on` field for jobs, adding new steps to build and deploy documentation, changing the working directory for some steps, and modifying the build command in the existing jobs.
> "New runners deployed,
> Docs now shine like a star,
> Code quality improved."
> chore: deploy docs on self hosted runners

- .github/workflows/attester.yml
- client/packages/attester/src/attester.ts
- client/packages/attester/tests/processAttestations.test.ts
Attestation will be removed from PendingConfirmation event after majority is reached + 6 blocks (batching window on t0rn)
Release Notes:
- New Feature: Added `attestationsDone` array to keep track of already done attestations and checks to skip attestation if it was already done or if the target is not allowed.
- Refactor: Removed unnecessary imports and code related to queuePurge().
- Test: Added unit tests for the `isAttestationDone` and `isTargetAllowed` methods of the `Attester` class.
> "Code changes abound,
Logic, security, and tests found,
Attentions paid all around,
Quality improved, let's astound!"
> feat: added attestationsDone array

- .github/PULL_REQUEST_TEMPLATE.md
Moved PR template from global .github repo to t3rn. 
It will be easier to introduce changes to it, scoped specifically to `t3rn` PRs.
Chore: Minor change to the PR template.
> "A small tweak to the template,
> Makes our process more complete."
> chore: move pr template to t3rn repo

- .github/workflows/attester.yml
- .github/workflows/executor.yml
- .github/workflows/grandpa-ranger.yml
Release Notes:
- New Feature: Added a new job to build a Docker image for Attester and modified the `deploy` job to only run on the `development` branch in `.github/workflows/attester.yml`.
- New Feature: Added a new `build-docker` job and modified the `deploy` job to only run on the `development` branch in `.github/workflows/executor.yml`. Moved AWS credentials configuration and ECR login steps after the executor build step in the `deploy` job.
- Chore: Added a condition to the `if` statement in the `build-docker` job in `.github/workflows/grandpa-ranger.yml`.
> Changes abound, deployment refined,
> Docker images built, AWS credentials aligned,
> A PR of chore and features combined,
> Celebrate we must, with joy enshrined.
> fix: deploy phase should not be run by dependabot

- client/packages/attester/pnpm-lock.yaml
- client/packages/cli/src/commands/register/gateway.ts
Fixes issue #1081
Need to call xdns.reboot_self_gateway before adding gateways (like `roco`).
Tested locally with standalone and works.
Release Notes:
- New Feature: Added a call to `xdns.rebootSelfGateway` before adding gateways, passing the `verificationVendor` parameter.
- New Feature: Added a call to `sdk.circuit.tx.signAndSendSafe` to sign and send the transaction.
> "With a reboot and a signature,
> Gateways now rise with vigor.
> Bugs are fixed, features shine,
> This PR brings code divine."
> fix: call reboot self gateway

- .github/workflows/cli.yml
- client/packages/cli/src/commands/register/gateway.ts
- client/packages/cli/src/utils/sfx.ts
- client/packages/executor/pnpm-lock.yaml
- client/packages/executor/src/attestationManager/index.ts
- client/packages/executor/src/bidding/index.ts
- client/packages/executor/src/circuit/listener.ts
- client/packages/executor/src/circuit/relayer.ts
- client/packages/executor/src/executionManager/execution.ts
- client/packages/executor/src/executionManager/index.ts
- client/packages/executor/src/executionManager/sideEffect.ts
- client/packages/executor/src/gateways/substrate/relayer.ts
- client/packages/executor/src/index.ts
- client/packages/executor/src/pricing/coingecko.ts
- client/packages/executor/src/prometheus.ts
Release Notes:
- Refactor: Updated logging throughout the codebase to use a shared logger module instead of `console.log`. Replaced `console.log` statements with appropriate logger method calls.
- Bug fix: Fixed Prometheus metric names and added new counters for executor bid monitoring and logging. Renamed existing counters for consistency.
- Chore: Updated command in CI workflow to use `pnpm test` instead of `yarn test`.
- Documentation: Added import statements and TypeScript compiler ignores for type definitions.
> "Code refactored, logs now shine bright,
> Metrics fixed, errors take flight.
> CI workflow dances with glee,
> Docs and imports, clearer to see.
> Changes abound, bugs no more,
> A release to celebrate, let's soar!"
> feat(executor): bid monitoring and logging

- primitives/src/circuit/types.rs
test: cover xtx id calculations for nonces 0,1 and 2
cover test cases to match the expected keccak hashes for nonces 0,1 and 2 at #1174 
Release Notes:
- Test: Added a new test case to cover the calculation of expected values for nonce 0, 1, and 2 in `primitives/src/circuit/types.rs`. It verifies transaction IDs and side effect IDs against expected hash values.
> "In the realm of tests, a new case emerges,
> Covering nonces with different surges.
> Hash values verified, expectations met,
> Bugs uncovered, no room for regret."
> test: cover xtx id calculations for nonces 0,1 and 2

- pallets/xdns/src/lib.rs
- pallets/xdns/src/tests.rs
```
**Refactor:**
- Added a new migration case to remove deprecated XDNS storage entries. This change ensures the system remains clean and efficient by eliminating outdated data.
**Test:**
- Introduced a test case `test_storage_migration_v144_to_v145_that_kills_old_xdns_records_entry()` to verify the successful removal of specific XDNS records during storage migration.
```
> Here's to the code that's lean and bright, 🌟  
> To the old records gone from sight. 🚀  
> With tests in place, we stand upright, 💪  
> Celebrating our code's new flight! 🎉
> fix: remove remaining deprecated XDNS records with storage migration

- pallets/rewards/src/lib.rs
Closes #1162 
**Refactor:**
- Moved the process of estimating treasury balances to the `on_initialize` hook in the rewards pallet.
- Added a return type to the `process_update_estimated_treasury_balance` function.
- Removed the call to `process_update_estimated_treasury_balance` from the `on_finalize` hook.
> 🎉 In the heart of our code, a change takes flight, 🚀
> Shifting balance estimates to initialize, oh what a sight! 👀
> Return types added, and finalize set right, ✅
> Our code dances with joy, basking in the light. 💃🕺
> fix: move process estimation of treasury balances to on_initialize hook

- runtime/t0rn-parachain/src/circuit_config.rs
On sepolia we have a lot of skipped votes. For this reason I am reducing the majority threshold to 67%, in effect unbricking the current light client instance
```
**Refactor:**
- Reduced the `CommitteeMajorityThreshold` constant from 80 to 67.
- Adjusted the majority threshold for `Eth2` and `Sepolia` configurations.
```
> Here's to the code that's leaner, not meaner 🎉
>
> With thresholds lowered, our system's keener 💡
>
> For `Eth2` and `Sepolia`, a change so serene,
>
> In this PR, a more efficient scene! 🚀
> fix: reduce majority threshold to unbrick LC

- runtime/t0rn-parachain/src/circuit_config.rs
fix: temporarily set 67% committee threshold to Eth2 light client, since we'll need to re-connect between Sepolia and Ethereum. 
**Refactor:**
- Adjusted the `CommitteeMajorityThresholdEth2` value from 80 to 67 in `runtime/t0rn-parachain/src/circuit_config.rs`.
> 🎉 A tweak, a change, a simple little shift,
> From 80 down to 67, giving our code a lift.
> Like a river's course subtly altered, it flows,
> In the realm of circuits, where the wild data grows. 🌱🌊💻
> fix: temporarily set 67% committee majority threshold to Sepolia light client 

- docs/main/docs/collator/testnet/testnet-collator.md
Should be merged after https://github.com/t3rn/t3rn/pull/1254
Docs are rewritten, making them more reasonable and easier to follow.
> docs: update documentation after polkadot 1.0.0 upgrade

- pallets/circuit/src/lib.rs
**Bug fix:**
- Corrected the conditional check in `pallets/circuit/src/lib.rs` to ensure `inclusion_receipt.height` is less than `fsx.submission_target_height`. This change fixes an issue where the condition was incorrectly checking for greater than.
> 🎉 Here's to the bugs we chase, 🐞
> 
> In the depths of code, a thrilling race. 💻
> 
> A flip of a sign, a simple twist, 🔀
> 
> Unravels mysteries in the mist. 🌫️
> 
> Celebrate this victory small, 🥳
> 
> For it makes a difference, after all! 🚀
> fix: inclusion_receipt.height should be lower than submission_target_height

- .github/workflows/attester.yml
- .github/workflows/cli.yml
- .github/workflows/executor.yml
- .github/workflows/grandpa-ranger.yml
- client/packages/cli/helm/values-t0rn.yaml
```
**Chore**: 
- Migrated Docker images from AWS to GitHub Container Registry (GHCR) across multiple workflows.
- Modified workflow, test job, build and publish Docker image steps, and deployment on EKS.
- Enhanced cli.yml with permissions for reading contents and writing packages, setting environment variables, adding concurrency settings, modifying job names, and a step to export variables.
```
> 🎉 In the realm of code, where logic is the key,
> A shift was made, as smooth as can be. 🚀
> From AWS to GHCR, the Docker images flew,
> Bringing enhancements, making everything new. 💫
> Concurrency set, permissions too,
> Celebrate this PR, for progress it drew! 🥳
> chore: move docker images from aws to ghcr

- .github/workflows/runtime-upgrade-t0rn.yml
Our current docker images are built with double `v` in front of the release number
Example: `ghcr.io/t3rn/t0rn-collator:vv1.48.4-rc.0`
**Bug fix:**
- Fixed the docker image name alignment in the `.github/workflows/runtime-upgrade-t0rn.yml` file by removing an extra 'v' character from the image tag.
> Here's to the bugs we chase, 🐞
> In code's vast and endless space. 💻
> A 'v' too many, a simple mistake, 🆚
> But oh, what difference does it make! 🎯
> Now fixed, aligned, all set to sail, 🚀
> On Docker's vast and windy gale. 🌬️
> So raise your glasses, let's give a cheer, 🥂
> For every bug that disappears! 🎉
> fix: docker image name aligned

- .github/workflows/runtime-upgrade-t0rn.yml
- collator.t0rn.Dockerfile
- collator.t3rn.Dockerfile
- docs/main/docs/collator/testnet/testnet-collator.md
**Refactor:**
- Updated Dockerfiles for `collator.t0rn` and `collator.t3rn` to create and assign ownership of directories `/node/data`, `/node/keystore`, `/node/specs`.
- Adjusted exposed ports in Dockerfiles.
- Removed the `--chown=runner` flag from `COPY` commands in `collator.t3rn.Dockerfile`.
**Documentation:**
- Fixed Docker image paths in `testnet-collator.md`.
- Updated Docker run command with new port mapping and path updates.
> 🎉 Ports are shifting, directories aligning,
> In Docker's realm, there's no room for whining.
> Paths corrected, documents refined,
> To the keen observer, no change left behind. 🚀
> fix: docker image paths and docs

- pallets/attesters/src/lib.rs
**New Feature:**
- Added a new event `AttestationTargetRemoved` to the pallet module.
- Updated the `remove_attestation_target` function for enhanced functionality.
**Test:**
- Introduced a new test case for removing and adding back attestation targets with sudo access.
> 🎉 Here's to the code that we've refined,  
> A new event in the pallet we find.  
> Attestation targets can now be removed,  
> With this update, our system improved.  
> Tests ensure our changes are aligned,  
> In our blockchain's fabric, they're intertwined. 🚀
> refactor: revisit and test attestation targets removal

- .github/workflows/cli.yml
- .github/workflows/npm-types.yml
- client/packages/attester/package.json
- client/packages/cli/package.json
- client/packages/executor/package.json
- client/packages/executor/src/circuit/listener.ts
- client/packages/executor/src/executionManager/index.ts
- client/packages/executor/src/utils/index.ts
- client/packages/types/package.json
- client/packages/types/yarn.lock
**Chore:**
- Updated GitHub Actions workflow in `cli.yml` for better code hygiene by removing an unnecessary empty line.
- Added a new GitHub Actions workflow in `npm-types.yml`. This workflow automatically publishes the `@t3rn/types` package to the npm registry when changes are pushed to the specified paths.
> 🎉 Here's to the workflows that weave,
> 
> In the codebase, they interleave. 🧵
> 
> With every push, they strive and strain,
> 
> To make our package rise like a plane! ✈️
> 
> So here's to `@t3rn/types`, may it reign! 👑
> ci: publish types to npm registry

- .github/workflows/attester.yml
- .github/workflows/cli.yml
- .github/workflows/executor.yml
- .github/workflows/grandpa-ranger.yml
- .github/workflows/npm-sdk.yml
- .github/workflows/update-dev-docs.yml
- client/attester.Dockerfile
- client/cli.Dockerfile
- client/executor.Dockerfile
- client/grandpa-ranger.Dockerfile
- client/packages/attester/README.md
- client/packages/attester/package.json
- client/packages/attester/pnpm-lock.yaml
- client/packages/cli/package.json
- client/packages/cli/pnpm-lock.yaml
- client/packages/executor/package.json
- client/packages/executor/pnpm-lock.yaml
- client/packages/executor/src/attestationManager/index.ts
- client/packages/executor/src/circuit/relayer.ts
- client/packages/executor/src/executionManager/sideEffect.ts
- client/packages/executor/src/gateways/substrate/relayer.ts
- client/packages/executor/src/index.ts
- client/packages/grandpa-ranger/package.json
- client/packages/grandpa-ranger/yarn.lock
- client/packages/sdk/package.json
**Refactor:**
- Updated GitHub Actions workflows for `attester`, `cli`, `executor`, and `grandpa-ranger` packages, refining the filters and commands.
- Added a new workflow to publish the @t3rn/sdk package to npmjs and deploy documentation to Vercel.
- Modified Dockerfiles for `attester`, `executor`, `cli`, and `grandpa-ranger`, adjusting the installed packages.
- Updated installation instructions in `attester` README.
**Bug fix:**
- Fixed type assertion when calling `signAndSendSafe` on a batch of transactions in `executor`.
> 🎉 Changes are here, making things clear, 🚀
> In code we trust, refactor we must. 💻
> With bugs now fixed, our code is mixed, 🐛
> Onward we sail, with wind in our sail! ⛵️🎉
> feat: add sdk to npmjs

- pallets/xdns/src/lib.rs
- pallets/xdns/src/tests.rs
**Refactor:**
- Modified the `destroy` function in the `pallet` module to check if the origin is the root account and set the `origin_admin` to the Escrow account before calling `T::AssetsOverlay::destroy`.
**Test:**
- Added a new test case `should_purge_token_and_destroy_asset_as_root_successfully` to verify the functionality of purging a token and destroying its associated asset when called by the root origin.
> 🎉 With roots that run deep, we've refined our sweep, 🧹
> Now tokens are purged, and assets submerged. 🌊
> Tests ensure we're on track, 🛤️
> Celebrate, there's no turning back! 🚀
> fix: derive admin origin set to Escrow for Root token destroys

- Cargo.lock
- node/standalone/Cargo.toml
- node/standalone/src/chain_spec.rs
- node/standalone/src/rpc.rs
- runtime/standalone/src/impl_versioned_runtime_with_api.rs
- Added the XDNS standard sfx ABI to the standalone chain specs in `node/standalone/src/chain_spec.rs`.
- Introduced `Xdns` and `Portal` RPC extensions in `node/standalone/src/rpc.rs`.
- Implemented runtime APIs for the `pallet_xdns` and `pallet_portal` modules in `runtime/standalone/src/impl_versioned_runtime_with_api.rs`.
**Deprecations:**
- Deprecated a function related to fetching ABIs in `runtime/standalone/src/impl_versioned_runtime_with_api.rs`.
> 🎉 With each line of code, we weave a tale,  
> Of gateways known and records that prevail.  
> The ABI's standard, now part of our quest,  
> In the world of XDNS, we're simply the best! 🚀
> chore: add XDNS standard sfx abi to standalone chain specs

- finality-verifiers/grandpa/src/lib.rs
- finality-verifiers/grandpa/src/light_clients.rs
- pallets/portal/src/lib.rs
- runtime/mock/src/circuit_config.rs
- runtime/standalone/src/circuit_config.rs
- runtime/t0rn-parachain/src/circuit_config.rs
- runtime/t1rn-parachain/src/circuit_config.rs
**Test:**
- Added a new test case `can_register_again_after_reset_with_valid_data_and_signer` to verify the registration process after a reset in the Grandpa Finality Verifier and Portal pallets.
**Chore:**
- Enhanced error handling in the `Portal` module by adding error logging when calling the `initialize` function. This will help in better debugging and understanding of any issues that may arise during initialization.
> 🎉 Here's to the code that never rests,  
> Testing registration after resets.  
> With logs for errors, clear as day,  
> We march ahead, come what may! 🚀
> fix: correct assignment for Polkadot and Kusama vendors and instances to runtimes

- finality-verifiers/grandpa/src/lib.rs
**Refactor:**
- Changed the storage maps `ImportedHeaders` and `ParachainIdMap` to use the `Identity` hasher instead of `Blake2_256`.
- Added functionality to drain the `ParachainIdMap` and `ImportedHeaders` storages under certain conditions.
> 🎉 With a change in hash, we make our dash,
> 
> From Blake to Identity, with much audacity.
> 
> Draining storages when conditions align,
> 
> In this PR's glory, we bask and shine! 🌟
> fix: drain imported headers at grandpa reset

- finality-verifiers/grandpa/src/lib.rs
**Test:**
- Added assertions to verify the behavior of `ImportedHeaders` and `ImportedHashes` data structures during a reset operation. This ensures that all expected keys are present in `ImportedHeaders` and `ImportedHashes` is empty post-reset.
> 🎉 Here's to the code that's now more robust, 🥂
> With tests for our data, in correctness we trust. 🛡️
> Reset operations, under the test's gaze, 👀
> Ensuring our structures, in order always stay. 🏗️
> test: check for drained ImportedHeaders at grandpa LC reset

- client/packages/grandpa-ranger/config/kusama.ts
- client/packages/grandpa-ranger/config/local.ts
- client/packages/grandpa-ranger/config/polkadot.ts
- client/packages/grandpa-ranger/config/rococo.ts
- client/packages/grandpa-ranger/helm/templates/deployment.yaml
- client/packages/grandpa-ranger/helm/templates/prometheusrule.yaml
- client/packages/grandpa-ranger/prettier.rc
- client/packages/grandpa-ranger/src/collect.ts
- client/packages/grandpa-ranger/src/index.ts
- client/packages/grandpa-ranger/src/prometheus.ts
**Refactor:**
- Removed the time interval between range submissions in `grandpa-ranger` configuration files.
- Added a new line of code to assign the difference between `targetHeight` and `circuitHeight` to `prometheus.heightDiff`.
- Removed a debug log statement related to batching ranges in the `GrandpaRanger` class.
- Added a metric to track the size of the transaction (`txSize`) using Prometheus.
- Modified the `/status` endpoint response status code based on the value of `heightDiff`.
**Style:**
- Introduced a new prettier configuration file for code formatting and style preferences.
> 🎉 Changes are here, no need to fear! 🚀
> Time intervals gone, the code is clear. 🧹
> Metrics now track, with no lack, 📊
> And style's on track, there's no going back! 🎨
> refactor(grandpa-ranger): submissions without interval

- Cargo.lock
- node/parachain/src/rpc.rs
- node/standalone/src/rpc.rs
- pallets/circuit/src/lib.rs
- pallets/circuit/src/machine/test.rs
- pallets/circuit/vacuum/src/lib.rs
- pallets/portal/rpc/Cargo.toml
- pallets/portal/rpc/runtime-api/Cargo.toml
- pallets/portal/rpc/runtime-api/src/lib.rs
- pallets/portal/rpc/src/lib.rs
- pallets/xdns/src/lib.rs
- primitives/src/circuit/traits.rs
- primitives/src/lib.rs
- runtime/mini-mock/src/lib.rs
- runtime/standalone/src/impl_versioned_runtime_with_api.rs
- runtime/t0rn-parachain/src/lib.rs
- runtime/t0rn-parachain/src/parachain_config.rs
- runtime/t1rn-parachain/src/lib.rs
- types/src/sfx.rs
- Added checks for above-zero target height increase in `pallets/xdns/src/lib.rs`.
- Introduced new test case `test_determines_none_for_two_non_increasing_elements` in `primitives/src/lib.rs`.
- Modified the `DisabledValidators` type in `runtime/t0rn-parachain/src/parachain_config.rs`.
- Updated import statements in `node/parachain/src/rpc.rs`, `node/standalone/src/rpc.rs`.
- Implemented new functions and methods related to side effects and transactions in `pallets/circuit/src/lib.rs`, `pallets/circuit/src/machine/test.rs`, `primitives/src/circuit/traits.rs`.
- Added a new function `fetch_all_active_xtx` to the `PortalRuntimeApi` trait and its implementations across multiple files.
- Removed a call to `XDNS::process_overview(System::block_number())` in …
> fix: check for above-zero target height increase before setting isActive

- .gitignore
- Cargo.lock
- runtime/common-pallets/Cargo.toml
- runtime/mini-mock/Cargo.toml
- runtime/standalone/Cargo.toml
- runtime/t0rn-parachain/Cargo.toml
- runtime/t1rn-parachain/Cargo.toml
Update sepolia pallet version to tag 1.1.3
The new version introduces multiple logs to debug track the submission of new sync committees.
**Chore**: Updated the sepolia pallet version to tag 1.1.3. This update includes the addition of a new text file.
> 🎉 A version, oh so new, we greet with cheer, 🥳
>
> To sepolia pallet, we've brought you near. 🚀
>
> With every update, our code takes flight, ✈️
>
> In the realm of software, a shining light. 💡
> chore: update sepolia pallet version to tag 1.1.3

- client/packages/cli/src/commands/fastWriter/index.ts
- client/packages/cli/src/commands/sfxABI/index.ts
Test warm up asset transfers in Roc to all reqistered gateways via Vacuum::singleOrder. 
CLI can be started with `pnpm cli mockWriter --as-sequential-tx` and with 1min breaks sends test orders for asset = 1 (rococo) out of Alice account.
> test: extend mock single vacuum order to test all registered gateways

- Cargo.lock
- runtime/common-pallets/Cargo.toml
- runtime/mini-mock/Cargo.toml
- runtime/standalone/Cargo.toml
- runtime/t0rn-parachain/Cargo.toml
* `v1.1.10` fixes linkage of execution ranges of Unsigned -> Signed epochs
> chore: update sepolia LC version 

- docs/main/docs/executor/become-an-executor/binary-setup.md
Added setup guides for Ubuntu/macOS and kept original format from website.
- Added Ubuntu installation steps
- Added macOS installation steps
- Added background process options (screen/tmux/systemd)
- Organized installation guides into existing docs
- Kept original welcome message and info blocks
- Added verification steps
All commands tested on Ubuntu 22.04 and macOS Sonoma.
Let me know if any changes needed! 👍
> Added Detailed guide for CLI Ubuntu/MacOS 
