t3rn/t3rn

gateway/pallet-escrow-gateway/balances/Cargo.toml, gateway/pallet-escrow-gateway/balances/src/lib.rs, gateway/pallet-escrow-gateway/balances/src/mock.rs, gateway/pallet-escrow-gateway/balances/src/tests.rs, gateway/pallet-escrow-gateway/escrow-engine/escrow-contracts/Cargo.toml, gateway/pallet-escrow-gateway/escrow-engine/src/lib.rs, gateway/pallet-escrow-gateway/escrow-engine/src/transfers.rs, gateway/pallet-escrow-gateway/escrow-engine/versatile-wasm/.gitignore, gateway/pallet-escrow-gateway/escrow-engine/versatile-wasm/Cargo.toml, gateway/pallet-escrow-gateway/escrow-engine/versatile-wasm/README.md, gateway/pallet-escrow-gateway/escrow-engine/versatile-wasm/src/code_cache.rs, gateway/pallet-escrow-gateway/escrow-engine/versatile-wasm/src/env_def/macros.rs, gateway/pallet-escrow-gateway/escrow-engine/versatile-wasm/src/env_def/mod.rs, gateway/pallet-escrow-gateway/escrow-engine/versatile-wasm/src/ext.rs, gateway/pallet-escrow-gateway/escrow-engine/versatile-wasm/src/gas.rs, gateway/pallet-escrow-gateway/escrow-engine/versatile-wasm/src/lib.rs, gateway/pallet-escrow-gateway/escrow-engine/versatile-wasm/src/plain_standards.rs, gateway/pallet-escrow-gateway/escrow-engine/versatile-wasm/src/prepare.rs, gateway/pallet-escrow-gateway/escrow-engine/versatile-wasm/src/runtime.rs
=> Implement Standards - versatile Wasm VM that integrates with runtime

.gitmodules, gateway/pallet-escrow-gateway/contracts-gateway/src/lib.rs, gateway/pallet-escrow-gateway/runtime-gateway/src/lib.rs
=> Create tools signing & dispatching calls with execution to Gateways

.gitmodules, gateway/demo-runtime/Cargo.lock, gateway/demo-runtime/node/Cargo.toml, gateway/demo-runtime/node/src/rpc.rs, gateway/demo-runtime/runtime/Cargo.toml, gateway/demo-runtime/runtime/src/lib.rs, gateway/pallet-escrow-gateway/contracts-gateway/src/lib.rs, gateway/pallet-escrow-gateway/contracts-gateway/src/tests.rs, gateway/pallet-escrow-gateway/runtime-gateway/src/lib.rs, gateway/test-integration/multistep_call.spec.js
=> Adapt compiler for !ink contracts to be compatible with Gateways

.github/workflows/circuit.yml, circuit/src/execution-delivery/src/lib.rs
In this PR I added sort to the `local_keys` vector
=> Refactor authority id selection - Fixes #59

circuit/Cargo.lock, circuit/src/chain_spec.rs, circuit/src/runtime/Cargo.toml, circuit/src/runtime/src/lib.rs
In this PR I added `pallet-circuit-execution-delivery` into runtime
=> Integrate pallet-circuit-execution-delivery into runtime

circuit/Cargo.lock, circuit/Cargo.toml, circuit/src/chain_spec.rs, circuit/src/runtime/Cargo.toml, circuit/src/runtime/src/lib.rs, circuit/src/service.rs
=> Relayers: Include beefy gadget as part of the circuit node - Closes #104

circuit/Cargo.lock, circuit/src/chain_spec.rs, circuit/src/runtime/Cargo.toml, circuit/src/runtime/src/lib.rs
=> Relayers: Add eth light client to runtime - Closes #105

.github/workflows/circuit.yml, .gitignore, circuit/Cargo.lock, circuit/Cargo.toml, circuit/pallets/beefy-merkle-tree/Cargo.toml, circuit/pallets/beefy-merkle-tree/src/lib.rs, circuit/pallets/beefy-mmr-pallet/Cargo.toml, circuit/pallets/beefy-mmr-pallet/src/lib.rs, circuit/pallets/beefy-mmr-pallet/src/mmr.rs, circuit/pallets/beefy-mmr-pallet/src/mock.rs, circuit/pallets/beefy-mmr-pallet/src/tests.rs, circuit/src/runtime/Cargo.toml, circuit/src/runtime/src/lib.rs, circuit/src/service.rs
=> Relayers: Add beefy mmr pallet - Closes #112

README.md, circuit/pallets/execution-delivery/src/lib.rs
=> Update licensing at main README.md

circuit/primitives/src/event_signature.rs, circuit/primitives/src/lib.rs, circuit/primitives/src/match_format.rs
=> Implement generic DFD decoder - Refers #119

circuit/primitives/src/lib.rs, circuit/primitives/src/match_format.rs, circuit/primitives/src/signature_caster.rs
=> Add signature codec for Side Effects Raw Headers - Closes #205

Cargo.lock, node/service/src/chain_spec/parachain.rs, node/service/src/chain_spec/standalone.rs, runtime/parachain/Cargo.toml, runtime/parachain/src/lib.rs, runtime/standalone/Cargo.toml, runtime/standalone/src/lib.rs
Closes https://github.com/t3rn/x-t3rn/issues/150, https://github.com/t3rn/x-t3rn/issues/151
=> Restore pallet-evm and pallet-contracts

.github/workflows/circuit-release.yml, docker/circuit-parachain.Dockerfile, docker/circuit.Dockerfile, node/cli/src/command.rs, node/service/src/chain_spec/standalone.rs, node/service/src/parachain.rs, node/service/src/standalone.rs, node/src/main.rs, pallets/contracts-registry/src/tests.rs, pallets/multi-finality-verifier/src/lib.rs, pallets/multi-finality-verifier/src/mock.rs
=> Clean up command.rs + fix circuit-release CI

node/parachain/src/chain_spec.rs, node/standalone/src/chain_spec.rs, runtime/parachain/src/lib.rs, runtime/standalone/src/lib.rs
fixes circuit panic issue in MFV
Locally, I still can't build without removing the `dev-dependency` flags in pallet-circuit. Anybody facing the same?
=> Add default MFV config to standalone and parachain

.github/PULL_REQUEST_TEMPLATE.md
This creates an initial PR template
As a follow on from this:
- commit to 3vm
=> docs: create initial pr template

client/types/README.md, client/types/package.json
Updated README for @t3rn/types
=> @t3rn/types: Update README with updated info and examples

docker/devnet/run.sh, docker/devnet/t3rn.Dockerfile
Final™️ fixes to improve devnet UX.
=> fix: maybe build 🐳 imgs b4 running 2 enable cold starts

client/grandpa-ranger/src/listeners/headers.ts, client/grandpa-ranger/src/listeners/relaychain.ts, client/grandpa-ranger/src/util.ts
Fixes the "invalid header detected" occuring when there are gaps in header ranges.
Relates #283
=> Fix invalid header ranges

.github/workflows/update_dev_docs.yml
Github action for generating and deploying rust docs. Still WIP but need to get something merged to test
=> WIP but need to test: Rust docs deployment action

docker/devnet/README.md, docker/devnet/docker-compose.yml, docker/devnet/run.sh
Fixes out of bounds p2p ports for `rococo-local` validators...
=> fix: out of bounds port

.github/workflows/update_dev_docs.yml
Adds docusaurus deployment to docs build action
=> adds vercel deployment to docs action

.github/workflows/pr-alert.yml
Fixes the actions condition syntax, missing tag, and trigger of the PR alert pipeline.
=> Fix the PR alert action

.github/workflows/collation-check.yml
Installs a missing WASM target for the collation check pipeline.
=> Install a WASM target for the collation check

Cargo.lock, pallets/contracts-registry/src/tests.rs, primitives/Cargo.toml, primitives/src/contract_metadata.rs, primitives/src/contracts_registry.rs
Adds a `KindValidator` for contract types
relates to t3rn/3vm#52
=> feat(3VM): Disallow contract characteristics

CODEOWNERS
This, coupled with approval of running actions in PR's for outside collaborators should increase our security for the runners.
I tried to keep this quite basic, adding sensible defaults where possible.
Helps https://github.com/t3rn/3vm/issues/88
=> Adds some initial codeowners

Cargo.lock, primitives/Cargo.toml
Uses sdk primitives from private registry, upgrade 3vm submodule
=> Remove SDK from 3vm and bumps the submodule

scripts/upgrade-runtime.sh
Brings back a functional `upgrade-runtime.sh`.
=> Cleanup any srtool customization

docs/t0rn-collator.md
+ Added t0rn faucet
+ Added some necessary steps to register_as_candidate 
+ Changed version to match the latest one
=> docs: add registration part to collator docs

docs/t0rn-collator.md
- Added argument to call rotateKeys
- Updated rotate key part
- Updated registration part
- Removed temp slot part
=> docs: update rotate keys part

.github/workflows/circuit.yml, Cargo.lock, pallets/circuit/src/lib.rs, pallets/circuit/src/mock.rs, pallets/circuit/src/tests.rs, primitives/src/match_format.rs, types/Cargo.toml, types/src/side_effect.rs
This pr transforms side effects from `LocalTrigger` to regular side effects that the protocol can validate.
=> feat: unify side effects between sdk and circuit 

.github/workflows/circuit.yml, Cargo.lock, pallets/circuit/Cargo.toml, pallets/circuit/src/lib.rs, pallets/circuit/src/tests.rs, primitives/Cargo.toml, primitives/src/circuit.rs, primitives/src/side_effect/mod.rs, primitives/src/threevm.rs, types/Cargo.toml, types/src/lib.rs, types/src/side_effect.rs
This enables the full e2e submission of SDK side effects as of `0.1.0`. At the moment we can only submit 1 due to some bug in SDK [here](https://github.com/t3rn/sdk/issues/17)
=> [DRAFT] Align side effects to SDK

collator.Dockerfile
Sets up a collator's data dir, specs dir, and keystore.
=> refactor: provide non-sensitive artifacts for collators

Cargo.lock, runtime/common-types/Cargo.toml, runtime/common-types/src/lib.rs
Add common runtime types as a separate Runtime crate
=>  Add common runtime types as a separate crate

pallets/account-manager/src/lib.rs, pallets/account-manager/src/manager.rs
Emit DepositReceived event from AccountManager since 3VM rely on it
=>  Emit DepositReceived event from AccountManager

.github/workflows/circuit.yml, .gitmodules, pallets/circuit/src/tests.rs
Update path to latest XBI Portal
=> Update path to latest XBI Portal

Cargo.lock, runtime/t0rn-parachain/Cargo.toml, runtime/t0rn-parachain/src/xcm_config.rs
Connect pallet Assets as Foreign Fungibles Transactor to XCM
=> Connect pallet Assets as Foreign Fungibles Transactor to XCM

Cargo.lock, node/t3rn-parachain/Cargo.toml, runtime/t3rn-parachain/Cargo.toml
Bump node and runtime shell versions to v1.0.0
=> Bump node and runtime shell versions to v1.0.0

docs/t0rn-collator.md
- added Docker Collator
- added Telemetry for Collators
=> docs: added docker collator and telemetry attribute

devnet/run-polkadot.sh, node/t3rn-parachain/src/chain_spec.rs, node/t3rn-parachain/src/command.rs, runtime/t3rn-parachain/src/parachain_config.rs
Update Shell addresses and set SS58 prefix to 9935
=> Update Shell addresses and set SS58 prefix to 9935

.dockerignore, .github/workflows/circuit-t0rn-collator-release.yml, .github/workflows/circuit-t3rn-collator-release.yml, CHANGELOG.md, collator.Dockerfile, docs/t0rn-collator.md, node/t0rn-parachain/Cargo.toml, node/t3rn-parachain/Cargo.toml, pallets/account-manager/src/lib.rs, pallets/account-manager/src/manager.rs, pallets/circuit/src/escrow/mod.rs, pallets/circuit/src/lib.rs, pallets/circuit/src/optimistic/mod.rs, pallets/circuit/src/state/mod.rs, pallets/circuit/src/tests.rs, pallets/circuit/src/weights.rs, primitives/src/side_effect/mod.rs, primitives/src/xtx.rs, runtime/mock/src/circuit_config.rs, runtime/standalone/src/circuit_config.rs, runtime/t0rn-parachain/src/circuit_config.rs, scripts/run-rococo-collators.sh, types/src/side_effect.rs
Executors bid for all Side Effect types
=> Executors bid for all Side Effect types 

docs/main/docusaurus.config.js, docs/main/src/components/HomepageFeatures/index.js
- fixed broken links in the footer
- updated old discord link
=> docs: fix broken links and update discord link

docs/main/docs/collator/mainnet/collator-requirements-mainnet.md
- remove false mainnet collator bond
=> docs: remove collator bond for mainnet

Cargo.lock, client/packages/.gitignore, client/packages/sdk/package.json, client/packages/sdk/src/circuit/index.ts, client/packages/sdk/src/circuit/tx.ts, client/packages/sdk/src/converters/address/substrate.ts, client/packages/sdk/src/converters/amounts.ts, client/packages/sdk/src/converters/utils.ts, client/packages/sdk/src/encodings/substrate/decoder.ts, client/packages/sdk/src/encodings/substrate/encoder.ts, client/packages/sdk/src/gateways/gateway.ts, client/packages/sdk/src/gateways/index.ts, client/packages/sdk/src/index.ts, client/packages/sdk/src/side-effects/index.ts, client/packages/sdk/tsconfig.json, client/packages/sdk/yarn.lock
This PR adds documentation and comments to @t3rn/sdk. It includes some tiny changes to `tsconfig.json` and  `package.json`
=> refactor: add documentation, comments and other configuration changes.

pallets/circuit/src/lib.rs
Fixes the multi sfx bidding issue that has been reintroduced somehow.
=> Fixes multi-sfx bids

client/packages/sdk/src/gateways/gateway.ts
Readds methods that were accidentally removed and required by the executor
=> Re-adds SDK conversion methods

client/packages/Makefile, client/packages/executor/README.md, client/packages/executor/yarn.lock, client/packages/sdk/yarn.lock
Adds a make file that builds the local packages. Run before installing dependencies for CLI or executor
=> Add makefile for local package building

pallets/circuit/src/lib.rs
Ensured that there aren't unsafe raw array indexing. All conditions were checked before indexing or used `.get(N)`.
Replaced `.unwrap()`s with `match` to log errors.
=> Checking for unsafe panicking and return errors

docs/main/docs/collator/testnet/collator-requirements-testnet.md, docs/main/docs/collator/testnet/testnet-collator.md, docs/main/docs/guides/faucet.md, docs/t0rn-collator.md
Newly deployed faucet is on address faucet.t0rn.io
More details https://github.com/t3rn/chainops/issues/17
=> docs: replace old faucet address with new one

.github/workflows/update_dev_docs.yml, .gitignore, client/packages/sdk/package.json, client/packages/sdk/src/circuit/tx.ts, client/packages/sdk/src/index.ts
Adds GH action for deploying SDK docs
=> Add ts-sdk doc deployemnt logic

.github/workflows/circuit-t0rn-collator-release.yml, docs/main/docs/collator/mainnet/mainnet-collator.md, docs/main/docs/collator/testnet/testnet-collator.md, docs/main/docs/guides/block-explorer.md, docs/main/rust/intro.md, docs/t0rn-collator.md, docs/t3rn-collator.md, rpc-test/src/extrinsic_gateway_remote.rs, scripts/enact-runtime-upgrade.sh
This PR is deprecating old DNS domain dev.net.t3rn.io in favour of t0rn.io
=> docs: update dev.net.t3rn.io to t0rn.io DNS

.github/workflows/circuit.yml, .github/workflows/zombienet-test.yml
This PR will refresh cache each morning for our self hosted github runners.
=> Add schedule to run build and zombienet test to keep cache warm

.github/workflows/pr-title-lint.yml
We should follow commitlint also on PR titles
=> fix: add PR title lint

.github/workflows/subalfred.yaml, Cargo.lock, runtime/t3rn-parachain/Cargo.toml, scripts/subalfred-check.sh
This PR will ease out maintenance of `subalfred` false positives
=> feat: update subalfred false positives list

.github/workflows/pr-title-lint.yml, scripts/subalfred-check.sh
This PR will fail subalfred check when it has errors while running `cargo`.
Currently it's only failing when `std` is found in subalfred output, so it's misleading on cargo errors.
Also PR Title shouldnt be checked on issues.
In case of cargo errors it will be visible in the comment and details in the GHA.
=> fix: subalfred errors out correctly

pallets/circuit/src/square_up/test.rs, pallets/circuit/src/tests.rs
fix: correct test expectations after existential deposit = 1 has been added
=> fix: correct test expectations after existential deposit = 1 has been added

.github/workflows/test-executor.yml, client/.dockerignore, client/Dockerfile, client/packages/executor/config/config.ts, client/packages/executor/package-lock.json, client/packages/executor/package.json, client/packages/executor/src/bidding/index.ts, client/packages/executor/src/executionManager/execution.ts, client/packages/executor/src/executionManager/index.ts, client/packages/executor/src/executionManager/sideEffect.ts, client/packages/executor/src/index.ts, client/packages/executor/src/pricing/coingecko.ts, client/packages/executor/tests/bidding.test.ts, client/packages/executor/tests/circuit.test.ts, client/packages/executor/tests/pricing.test.ts, client/packages/executor/tests/strategy.test.ts, client/packages/sdk/src/side-effects/types.ts, client/packages/sdk/yarn.lock
chore: create pull request
- Extends bidding engine's features. 
- Adds tracking between side effects and bidders.
-  Adds scenarios for the executor to behave differently based on some configuration. 
- Adds configuration loading. 
- Adds cleaning for the Maps tracking relationships between sfx and bidders. 
- Adds tests for the new features, and tests for previous code.
Tests can, and should, be extended.
=> feat: extend bidding engine

Cargo.lock, docs/main/docs/collator/testnet/testnet-collator.md, node/t0rn-parachain/Cargo.toml, runtime/t0rn-parachain/Cargo.toml, runtime/t0rn-parachain/src/parachain_config.rs, runtime/t3rn-parachain/src/parachain_config.rs
loosen collators config MaxCandidate and SessionTime
=> fix: loosen collators config MaxCandidate and SessionTime

docs/main/docs/collator/mainnet/mainnet-collator.md, docs/main/docs/collator/testnet/testnet-collator.md
=> docs: add --state-cache 0 to collator instructions

.github/workflows/release-t0rn.yml, CHANGELOG.md, scripts/upgrade-runtime-unsafe.sh
This PR makes final touches to CICD in prepartions
Explicitly say which hash for WASM is checked
Sklip waiting when it's dry run 
=> build: t0rn dry run deploy preparation

runtime/t0rn-parachain/src/lib.rs, runtime/t3rn-parachain/src/lib.rs
log new validation code hash before submitting to Relay in runtime RPC
Closes #617 
=> chore: log new validation code hash before submitting to Relay in runtime RPC

scripts/schedule-authorize-runtime-upgrade.js, scripts/upgrade-runtime-unsafe.sh, scripts/upgrade-runtime.sh
Refactors runtime upgrade scripts to use `scheduler.scheduleAfter(100, ...)`.
Closes https://github.com/t3rn/t3rn/issues/615
=> refactor: runtime upgrades use scheduler.scheduleAfter(100, ...)

.github/workflows/circuit-t0rn-collator-release.yml, .github/workflows/circuit-t3rn-collator-release.yml, .github/workflows/circuit.yml, .github/workflows/subalfred.yaml, .github/workflows/update_dev_docs.yml, .github/workflows/zombienet-test.yml
This PR updates rust toolchain version in preparation for polkadot v37.
=> build: update rust toolchain version to nightly-2023-01-24

.github/workflows/release-t0rn.yml, scripts/upgrade-runtime-set-code.sh
This PR introduces a script that will do runtime ugprade with setcode method.
=> build: script for setcode runtime upgrade

.github/workflows/release-t3rn.yml
Github is not very explicit about where GHA should be located, on which branch
> A workflow run is triggered for any workflows that have on: values that match the triggering event. **Some events also require the workflow file to be present on the default branch** of the repository in order to run.
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#about-workflow-triggers
=> build: gha to release t3rn

runtime/t3rn-parachain/src/system_config.rs
Fixes an issue where we can have dos based on cheap tx.
=> fix(t3rn): add slow adjusting fee 

.github/SPRINT_TEMPLATES/sprint-goal.md
propose a new sprint goal template
=> docs: propose a new sprint goal template

runtime/mock/src/system_no_version_config.rs, runtime/standalone/src/signed_extrinsics_config.rs, runtime/standalone/src/system_config.rs, runtime/t0rn-parachain/src/signed_extrinsics_config.rs, runtime/t0rn-parachain/src/system_config.rs
Splits foreign asset fees 80% to author, 20% to treasury. 
=> feat: foreign fee split

client/packages/cli/commands/register/substrate.ts, client/packages/cli/commands/submit_header/submit_header.ts, client/packages/cli/commands/submit_header/substrate.ts, client/packages/cli/index.ts, client/packages/cli/package.json, client/packages/cli/yarn.lock, client/packages/sdk/yarn.lock
Adds basic logging to enable the monitoring of the ranger on roco.
=> feat: add logging to ts-sdk for ranger monitoring

.github/workflows/executor-deploy.yml
This PR fixes wrong image path for executor. 
=> ci: fix deploying executor

scripts/subalfred-check.sh
This PR changes subalfred checks output to better understand if its green or red.
=> ci: subalfred script revamped

.github/workflows/release-t0rn.yml, scripts/upgrade-runtime-set-code.sh
This PR introduce approval step before t0rn runtime upgrade.
=> ci: t0rn runtime upgrade with an approval

.github/workflows/release-t0rn.yml, Cargo.lock, docs/main/docs/collator/testnet/testnet-collator.md, node/t0rn-parachain/Cargo.toml, runtime/t0rn-parachain/Cargo.toml, runtime/t0rn-parachain/src/lib.rs
update manifests to v1.3.0-rc.0
=> build: update manifests to v1.3.0-rc.0

.github/workflows/release-t0rn.yml, scripts/upgrade-runtime-set-code.sh
=> ci: remove script code that removes wasm binary during dry-run

.github/workflows/release-t0rn.yml, scripts/upgrade-runtime-set-code.sh
=> ci: dont convert wasm blob to hex on dry run

scripts/upgrade-runtime-set-code.sh
=> ci: fix if conditional for dry run upgrade

client/packages/sdk/src/index.ts
=> refactor: sdk await wasm crypto ready

.github/workflows/ranger-deploy.yml, client/cli.Dockerfile, client/packages/cli/helm/Chart.yaml, client/packages/cli/helm/templates/_helpers.tpl, client/packages/cli/helm/templates/cronjob.yaml, client/packages/cli/helm/templates/serviceaccount.yaml, client/packages/cli/helm/values-t0rn.yaml, client/packages/cli/index.ts
This PR introduce running cli ranger as a cronjob.
=> ci: ranger deployment

client/packages/executor/helm/values.yaml
This PR updates WS endpoint for executors.
=> chore: executors should connect to ws t0rn

client/packages/cli/commands/register/substrate.ts
fixes type error that pops up as a result of the new types package when using cli as ranger.
=> fix: cli type error

pallets/circuit/src/lib.rs, pallets/circuit/src/machine/test_extra.rs, pallets/circuit/src/machine/test_extra_stress.rs, pallets/circuit/src/tests.rs, primitives/src/xtx.rs, runtime/mock/src/test_utils.rs, types/src/fsx.rs, types/src/sfx.rs
Small refactor for aligning and renaming the sfx action field and type. This introduces a custom alias, preventing us from doing a bunch of unsafe conversions down the line. 
=> refactor: sfx action field

Cargo.lock, pallets/circuit/src/lib.rs, pallets/evm/src/benchmarking.rs, pallets/executors/Cargo.toml, pallets/executors/src/lib.rs, runtime/mock/src/xbi_config.rs, runtime/t0rn-parachain/src/xbi_config.rs
Installs XBI `37`, see [changelog](https://github.com/t3rn/xbi/blob/main/CHANGELOG.md)
Need to verify on zombienet manually before happy for it to go.
=> feat: install xbi 0.9.37

client/packages/cli/helm/templates/cronjob.yaml, client/packages/cli/helm/values-t0rn.yaml
This PR introduce timeout for ranger. 
If it will run for more than 5 minutes then it will be automatically restarted.
=> build: add timeout for running ranger cronjob

.github/dependabot.yml
=> chore: create .github/dependabot.yml

.github/dependabot.yml, .github/workflows/dependabot-validate.yml
This pull request fixes dependabot config.
✅ GHA .github/dependabot.yml — Dependabot config file validation
=> build: fix dependabot config

pallets/3vm/src/mock.rs, pallets/circuit/src/tests.rs, pallets/contracts/src/tests.rs, pallets/contracts/src/tests/threevm/mock.rs, pallets/evm/src/tests/threevm/mock.rs, runtime/mock/src/circuit_config.rs
=> fix: 3vm mocks

.gitattributes
This should exclude nodejs lock files from GH insights.
=> build: disable scanning yarn.lock and package.lock by gh

.github/dependabot.yml, .github/workflows/circuit.yml, .github/workflows/dependabot-validate.yml, .github/workflows/executor-deploy.yml, .github/workflows/release-t0rn.yml, .github/workflows/runtime-upgrade-t0rn.yml, .github/workflows/subalfred.yaml, .github/workflows/update-dev-docs.yml, .github/workflows/zombienet-test.yml
PR required checks will be triggered and pass even for PRs without required path changes.
- fixes and improvents to other GHA
=> build: pr required checks [skip release]

.github/workflows/lint-commits.yml
Commitlint will now pass on long lines exceeding default body-max-line-length, like ones from dependabot.
=> build: commitlint should ignore some rules for dependabot [skip release]

.github/workflows/dependabot-update.yml
=> build: dependabot update cargo happens on correct branch [skip release]

.github/workflows/circuit.yml, .github/workflows/dependabot-update.yml, .github/workflows/release-t0rn.yml, .github/workflows/runtime-upgrade-t0rn.yml, .github/workflows/zombienet-test.yml
This set rust toolchain to same version across all github actions.
For previous toolchain it was failing with:
```
error[E0658]: `let...else` statements are unstable
--> /github-runner/.cargo/registry/src/github.com-1ecc6299db9ec823/scale-info-2.5.0/src/portable.rs:129:17
|
129 | /                 let Some(ty) = &param.ty else {
130 | |                     continue
131 | |                 };
| |__________________^
|
= note: see issue #87335 <https://github.com/rust-lang/rust/issues/87335> for more information
= help: add `#![feature(let_else)]` to the crate attributes to enable
Compiling rtnetlink v0.10.1
Compiling sp-version-proc-macro v4.0.0-dev (https://github.com/paritytech/substrate.git?branch=polkadot-v0.9.27#5bfdbab8)
For more information about this error, try `rustc --explain …
```
=> fix: update rust toolchain

.github/workflows/executor.yml, .github/workflows/runtime-upgrade-t0rn.yml
We have helm on our self hosted runners
=> build: fix gha for executor and ranger deploy

client/packages/executor/helm/templates/deployment.yaml, client/packages/executor/helm/templates/pvc.yaml, client/packages/executor/helm/values.yaml
Executor is already deployed with persistent 1GB storage at `/data` path
=> build: add persistent storage to executor [skip release]

.github/workflows/release-t0rn.yml, .github/workflows/semantic-version.yml, scripts/build_wasm.sh
Submwasm is preinstalled so no point in building it.
Also we can upload whole output of subwasm as release asset.
=> build: subwasm is preinstalled on github runners

primitives/src/light_client.rs
Exposes the types and trait needed for implementing the light client trait. This solves some import issues I had when importing from the trait dir directly. 
=> feat: expose entire light client trait in primitives

types/abi/src/sfx_abi.rs
=> fix: append prefix memo to SFX validation only if set

tests/zombienet/zombienet.sh
This PR speeds up setting up zombienet as it doesn't require fetching ~200MB binary each time it's run.
Additionally logs are grouped with time measurement and zombienet was updated to the latest.
=> build: use already present zombienet and polkadot binaries during tests [skip release]

.github/dependabot.yml
This PR introduce more dependabot dependency updates for rust.
=> build: more dependabot updates for rust packages [skip release]

codecov.yml
Currently codecov threshold is set to 70% which means that all builds will be failing project codecov until our 62% won't improve.
Reducing it will make it green and is a good starting point for continuous improvements in code coverage.
=> build: decrease codecov threshold [skip release]

.github/workflows/subalfred.yml
This PR fixes errors during execution subalfred github action due to lack of permissions.
=> build: fix usage of this gha for dependabot [skip release]

.github/workflows/test-cargo-release.yml, node/t3rn-parachain/Cargo.toml, runtime/t3rn-parachain/Cargo.toml
This PR fixes cargo dependencies (again) and add a dry run for cargo release in our GHA.
=> build: fix cargo dependencies for a release

collator.t0rn.Dockerfile, collator.t3rn.Dockerfile
This PR fixes wrong entrypoint which would give error 
```
polkascan-collator-1        | /usr/local/bin/t0rn-collator: /usr/local/bin/t0rn-collator: cannot execute binary file
```
And upgrade ubuntu to fix problem with libssl
```
polkascan-collator-1   | /usr/local/bin/t0rn-collator: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```
=> build: t0rn/t3rn dockerfile fixes

.github/workflows/runtime-upgrade-t0rn.yml
This PR ensures that only one runtime upgrade can be in progress. 
=> build: ensure single runtime upgrade in progress [skip release]

.github/workflows/test-circuit.yml
This PR improve strategy to cancel builds when there is new commit.
It still should happen but not on development branch where we want all builds to finish.
=> build: dont cancel circuit builds on development [skip release]

.github/workflows/test-circuit.yml
Currently if cargo clippy fails, the pipeline will go forward and run all tests which will fail as well.
This PR introduce fail fast when clippy detect errors.
=> build: cargo clippy fail fast [skip release]

.github/workflows/runtime-upgrade-t0rn.yml
This PR adds more approvers for runtime upgrade.
Anybody from t3rn dev team can now initiate it.
=> build: add more people as approvers for runtime upgrade

Cargo.lock, pallets/account-manager/src/manager.rs, pallets/circuit/src/square_up/mod.rs, primitives/src/account_manager.rs
- remove the fallible finalize, rely solely on infallible finalize version:
- no 1% rewards claim on successful transfers for EscrowAccount - 100% goes to either executor or requester 
- revert step leaves no Settlement
- finalize should never fail 
- remove on-claimable logic since staking for executors is dropped
- optimize deposit_batch for less cloning and use Vec::with_capacity to keep the size control 
=> refactor: remove dropped finalize + claimable behaviours & optimise Account Manager

CODEOWNERS
This PR change who will be default reviewer for t3rn code. Currently each PR that has changes in directories not included in CODEOWNER file will add only @MaciejBaj as required reviewer. By default this should be whole team and for specific directories we can have additional reviewers required.
Feel free to propose changes
=> build: changes to CODEOWNER [skip release]

.github/workflows/runtime-upgrade-t0rn.yml
Currently our zombietests want to run when new release is created but it takes time to build and upload relevant artifacts.
Because of that it should wait for release to finish.
=> build: runtime upgrade should wait for a release

.github/workflows/executor.yml
This PR will make executor check required step even for PRs not changing node.
=> build: cicd require executor tests [skip release]

.github/labeler.yml
This PR improve automatic PR labeler
=> build: cicd improve PR labeling [skip release]

README.md
=> build: update year in README.md [skip release]

.github/workflows/executor.yml, .github/workflows/update-dev-docs.yml, client/packages/executor/package.json, client/packages/executor/src/utils/index.ts, node/standalone/Makefile
This fixes error during executor build docs
=> build: cicd fix eslint executor [skip release]

CODEOWNERS
=> build: allow @t3rn/dev to approve [skip release]

Cargo.lock, node/standalone/src/chain_spec.rs, node/t0rn-parachain/src/chain_spec.rs, pallets/account-manager/src/manager.rs, pallets/contracts/src/storage.rs, runtime/standalone/Cargo.toml, runtime/standalone/src/lib.rs, runtime/standalone/src/system_config.rs, runtime/t0rn-parachain/Cargo.toml, runtime/t0rn-parachain/src/lib.rs, runtime/t0rn-parachain/src/system_config.rs
- chore: port from cumulus
- chore: last pass before correct install
- feat: configure mm pallet to disallow some calls
- chore: port maintenance to standalone
Add the functionality to enter the runtime into maintenance mode and
block the execution of some calls, while allowing the execution of
vital calls.
=> feat: add maintenance mode to runtime

.github/workflows/executor.yml
Without those permissions executor cicd will fail when dependabot will trigger it.
=> build(cicd): add required permissions to executor workflow [skip release]

client/packages/cli/README.md, client/packages/cli/index.ts
This fixes error during CLI execution
```
TSError: ⨯ Unable to compile TypeScript:
index.ts:121:47 - error TS2339: Property 'setOperational' does not exist on type '{ registerGateway: AugmentedSubmittable<(gatewayId: string | Uint8Array | U8aFixed, tokenId: string | Uint8Array | U8aFixed, verificationVendor: number | "Rococo" | ... 4 more ... | "Kusama", executionVendor: number | ... 3 more ... | T3rnPrimitivesExecutionVendor, codec: number | ... 3 more ... | "Rlp", registrant:...'.
121             const tx = this.circuit.tx.portal.setOperational(transactionArgs?.gatewayId, transactionArgs?.operational);
~~~~~~~~~~~~~~
at createTSError (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:859:12)
at reportTSError (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:863:19)
at getOutput …
```
=> fix: cli shoud not have set-operational [skip release]

client/grandpa-ranger/src/index.ts, client/packages/cli/src/cli.ts, client/packages/cli/src/commands/bid.ts, client/packages/cli/src/commands/submit/headers.ts, client/packages/cli/src/schemas/setup.ts, client/packages/cli/src/templates/setup.ts, client/packages/cli/yarn.lock
=> fix: submit headers & bid process.exit

.github/workflows/executor.yml, client/packages/executor/src/gateways/substrate/estimator/index.ts, client/packages/executor/src/gateways/substrate/relayer.ts
=> fix: executor docs build issue [skip release]

.github/workflows/cli.yml, .github/workflows/executor.yml, client/cli.Dockerfile, client/cli_entrypoint.sh, client/contracts/deploy.ts, client/executor.Dockerfile, client/packages/cli/helm/Chart.yaml, client/packages/cli/helm/templates/_helpers.tpl, client/packages/cli/helm/templates/cronjob.yaml, client/packages/cli/helm/templates/serviceaccount.yaml, client/packages/cli/helm/values-t0rn.yaml, client/packages/cli/index.ts, client/packages/cli/src/templates/setup.ts, client/packages/cli/src/utils/circuit.ts, tests/zombienet/zombienet.sh
This PR fixes cli Dockerfile after revamp changes
Additionally it builds images in ci workflow to prevent situation where Dockerfile is broken
=> build: cli and executor Dockerfile build [skip release]

client/packages/cli/src/commands/submit/headers.ts, runtime/t0rn-parachain/src/lib.rs
=> fix: expose portal rpc endpoint in t0rn runtime

Cargo.lock, node/t0rn-parachain/Cargo.toml, node/t0rn-parachain/src/rpc.rs, node/t0rn-parachain/src/service.rs
=> feat: activate portal rpc service in t0rn runtime

client/packages/cli/.gitignore, client/packages/cli/README.md, client/packages/cli/src/cli.ts, client/packages/cli/src/commands/bid.ts, client/packages/cli/src/commands/register/gateway.ts, client/packages/cli/src/commands/register/register.ts, client/packages/cli/src/commands/submit/headers.ts, client/packages/cli/src/commands/submit/sfx.ts, client/packages/cli/src/commands/submit/submit.ts, client/packages/cli/src/utils/circuit.ts, client/packages/cli/yarn.lock, client/packages/sdk/src/circuit/index.ts, client/packages/sdk/src/circuit/tx.ts, client/packages/sdk/src/export/index.ts, client/packages/sdk/yarn.lock
=> feat: implement export extrinsic data to file

.github/workflows/cli.yml, .github/workflows/executor.yml, .github/workflows/semantic-version.yml, client/packages/cli/package.json, client/packages/executor/package.json
`eslint` errors and warning will now be annotated in PR code changes.
This will force to fix current errors when code will be revisited.
=> build: add eslint report and annotations

Cargo.lock, finality-verifiers/grandpa/src/lib.rs, finality-verifiers/grandpa/src/light_clients.rs, finality-verifiers/grandpa/src/mock.rs, pallets/3vm/src/precompile.rs, pallets/circuit/src/lib.rs, pallets/portal/Cargo.toml, pallets/portal/src/lib.rs, pallets/portal/src/tests.rs, pallets/xdns/src/tests.rs, primitives/src/light_client.rs, primitives/src/portal.rs, runtime/common-pallets/Cargo.toml, runtime/common-pallets/src/lib.rs, runtime/mock/src/circuit_config.rs, runtime/mock/src/lib.rs, runtime/standalone/Cargo.toml, runtime/standalone/src/circuit_config.rs, runtime/standalone/src/impl_versioned_runtime_with_api.rs, runtime/standalone/src/lib.rs, runtime/t0rn-parachain/Cargo.toml, runtime/t0rn-parachain/src/circuit_config.rs, runtime/t0rn-parachain/src/lib.rs
- adds pallet to runtimes
- adds tests to portal, to ensure pass-through is working
- clean up LightClient trait
- 
=> feat: impl eth2 pallet

.github/workflows/auto-summary.yml
Release Notes:
- Chore: Added a new GitHub Actions workflow.
> "A new workflow has arrived,
> No code changes, no need to strive.
> A chore it may be,
> But it brings us glee."
=> build: add automatic summary to PRs [skip release]

client/packages/cli/src/commands/submit/sfx.ts, client/packages/cli/src/schemas/sfx.ts
Release Notes:
- Refactor: Changes to `mapEncodedArgs` function and `SideEffectSchema` in `sfx.ts` file introduce an enum for the `action` parameter instead of a string. The `SideEffectSchema` now uses an enum validation for the `action` field and adds a new type `SideEffectAction` and a constant object `SideEffectActions` that maps to the possible values of `action`.
> "Enums bring clarity,
> Strings can be quite scary.
> With SideEffectActions,
> Bugs will face …
=> refactor: sfx actions

.github/workflows/grandpa-ranger.yml, client/packages/grandpa-ranger/helm/templates/servicemonitor.yaml, client/packages/grandpa-ranger/helm/templates/svc.yaml
Release Notes:
- Chore: Uncomment `if` condition for deployment to only happen on `development` branch in `.github/workflows/grandpa-ranger.yml`.
> "Uncommented if, oh what a relief,
> Deployment now happens only on development's belief."
=> feat(grandpa-ranger): monitoring

runtime/t0rn-parachain/Cargo.toml, runtime/t0rn-parachain/src/system_config.rs
Correctly replace the old BaseCallFilter for the 
one provided by the MaintenanceMode pallet.
Release Notes:
- Bug fix: Fixed a race condition in the login process that caused intermittent failures.
> "A bug was found and fixed,
> Login process now flows slick,
> No more race conditions to mix,
> Our code is now a solid brick."
=> fix: add correct filter

Cargo.lock, pallets/attesters/Cargo.toml, pallets/attesters/README.md, pallets/attesters/src/lib.rs, pallets/xdns/src/lib.rs, primitives/src/attesters.rs, primitives/src/xdns.rs, runtime/mini-mock/src/lib.rs, runtime/mock/src/circuit_config.rs, runtime/standalone/src/circuit_config.rs, runtime/t0rn-parachain/src/circuit_config.rs
Release Notes:
- New Feature: Added a Substrate module for managing attesters in a blockchain network. Provides APIs for registering attesters, nominating them, and handling slash risks. Includes examples of how to call the functions using Polkadot.js.
- New Feature: Added a new function to get the target codec for a given chain ID.
- Chore: Added new types and traits to the codebase, as well as a mock implementation of one of the traits. Defined some constants …
=> feat: batch attestations per target for committee transitions, penalties and SFX

client/packages/grandpa-ranger/config/local.ts, client/packages/grandpa-ranger/config/roco.ts, client/packages/grandpa-ranger/src/collect.ts, client/packages/grandpa-ranger/src/index.ts, client/packages/grandpa-ranger/yarn.lock, finality-verifiers/grandpa/src/lib.rs
We have reached a rare edge case, where the signed header is also the last one of its epoch. In this case, we where not able to submit new headers. This PR fixes the edge case.
Release Notes:
- Bug fix: Fixed an edge case in `collect.ts` where new headers could not be submitted if the signed header was also the last one of its epoch.
- Refactor: Removed the signer key from the configuration object in `local.ts`.
- Chore: Exported an object with configuration parameters for a circuit in `roco.ts`.
> "Bugs were …
=> fix: grandpa range edge case

.github/dependabot.yml
Release Notes:
- New Feature: The `calculateSum` function has been updated to handle negative numbers correctly, improving the correctness and reliability of the function.
- Refactor: The `calculateSum` function has been refactored to use the `reduce` method instead of a for loop, simplifying the code and making it more readable. Error handling has also been added to ensure that the function returns an error message if the input is not an array of numbers.
- …
=> ci(dependabot): add cli for automated version update

.github/dependabot.yml
Release Notes:
- New Feature: Added support for fetching dependencies from private GitHub repositories.
- New Feature: Specified the number of open pull requests limit and schedule interval for updating cargo packages.
> "Private repos, no longer a woe,
> Dependabot now fetches with ease, you know.
> Cargo packages, always up-to-date,
> With limits set, no need to wait."
=> ci(dependabot): fix fetching dependencies from pirvate repos

.github/workflows/release-t0rn.yml, .github/workflows/semantic-version.yml, specs/rococo.raw.json
This PR replaces all unavailable bootnodes for roco and replace them with current ones.
Changes from:
https://github.com/paritytech/polkadot/blob/master/node/service/chain-specs/rococo.json
Chore: Add new file patterns to trigger GitHub action
This pull request adds two changesets that only add a new file pattern to the list of files that trigger the GitHub action. These changes do not affect the code logic or functionality and are safe to approve.
> "New file patterns added,
> GitHub action now triggered.
> Code logic remains safe."
=> fix(chainspecs): replace outdated bootnodes for rococo

.github/workflows/attester.yml, client/packages/attester/src/attester.ts
Release Notes:
- Bug fix: Change log level of an info message to debug in `attester.ts`.
- Chore: Review the commented out condition for a deployment job in `attester.yml`.
> "A bug was found and quickly fixed,
> With thorough review, we won't be mixed.
> Our code is cleaner, our logs are clear,
> Thanks to our diligent engineer."
=> fix(attester): info logs for events are spamming

pallets/xdns/src/lib.rs, pallets/xdns/src/tests.rs, pallets/xdns/src/weights.rs
New Feature: The XDNS module now includes a `reboot_self_gateway` extrinsic, allowing the root to add or re-add a self-gateway with a specified vendor. Two new tests were added to ensure proper functionality. 
> "XDNS module, oh so grand,
> Now with reboot at your command.
> Add or re-add with ease,
> And test it all, if you please."
=> fix: add reboot self gateway extrinsic to XDNS

client/packages/cli/src/commands/register/gateway.ts, client/packages/sdk/src/gateways/index.ts
Release Notes:
Chore: A minor change was made to the `initGateways` function in `index.ts` to skip a specific gateway entry during initialization. 
> "A small tweak to the code,
> Ignoring gateways with a simple node.
> A chore, not a feature or fix,
> But still important to triage and mix."
=> fix: sdk ignores local gateway entry

Cargo.lock, pallets/attesters/src/lib.rs, primitives/src/attesters.rs, runtime/mini-mock/src/lib.rs
@open_ai ignore
Release Notes:
- New Feature: Refactored `Attesters` module to check for XDNS entry existence and added permanent slash value. Modified `LatencyStatus` enum, `PermanentSlashes` storage map, and `read_attestation_latency` function.
- Bug fix: Removed `PendingSlashes` struct and added `PermanentSlashes` struct in `pallet_attesters` module.
> "Code changes abound,
> Attesters module refactored sound,
> Bugs fixed, new features found,
> Blockchain …
=> refactor: check XDNS entry exists before adding as attestation targets + permanent slash as StorageValue

Cargo.lock, pallets/rewards/src/lib.rs
Customise max rewards executors kickback and default to zero. Abandon 90% max reward subsidise 
Release Notes:
- New Feature: Customize max rewards executors kickback and default to zero
- New Feature: Add new function `set_max_rewards_executors_kickback`
- Bug fix: Abandon 90% max reward subsidize
- Test: Update tests
This changeset introduces the ability to customize the max rewards executors kickback and adds a new function to set the kickback value. The 90% max reward subsidize has been abandoned, and the …
=> refactor: customise max rewards executors kickback and default to zero

.github/workflows/auto-review.yml
Adds a review when label review is added
Release Notes:
- Refactor: Modularized main logic, added error handling, improved performance, fixed data races, optimized code, and improved security in `main.rs`.
- Chore: Added GitHub Actions workflows for PR review using `openai-pr-reviewer` in `.github/workflows/auto-review.yml` and `.github/workflows/auto-summary.yml`.
> "Code quality improved,
Modularized and optimized.
GitHub Actions help."
=> chore: run review only when label is added

pallets/attesters/src/lib.rs
Release Notes:
- Bug fix: Changes to the quorum and full_approval calculation in two functions in `pallets/attesters/src/lib.rs` now use `CommitteeSize` instead of `ActiveSetSize`.
> "From ActiveSetSize to CommitteeSize,
> A bug was fixed with ease.
> With new logic in place,
> Bugs and vulnerabilities we erase."
=> fix: quorum calculates Committee not ActiveSet size

.github/workflows/executor.yml
Bug fix: Fixed a race condition in the `process_data` function that caused incorrect results. 
> "Bugs were squashed, code was fixed,
> Results are now accurate and mixed.
> With this PR, we celebrate
> A better codebase, let's elevate!"
=> fix: executor deploy step

.github/workflows/grandpa-ranger.yml
Chore: Minor change to a GitHub Actions workflow file.
> "A small tweak to our actions,
> Keeps our workflows in traction."
=> chore(grandpa-ranger): types/SDK changes should trigger deploy

.github/workflows/check-lock-files.yml
Checks if there are lock files for NPM and PNPM.
Only one package manager is allowed: YARN.
Bug fix: The code now checks for the presence of `package-lock.json` and `pnpm-lock.yaml` files and exits with an error if either file exists. It incorporates changes to improve compatibility with all POSIX shells and uses the `fail()` function provided by GitHub Actions for better visibility and integration.
> "Code improved, bugs removed,
> Lock files checked, errors proved.
> POSIX shells, compatibility embraced,
> GitHub Actions, better integration traced."
=> chore: only one package manager to rule them all [skip release]

Cargo.lock, Cargo.toml, finality-verifiers/grandpa/src/light_clients.rs, pallets/attesters/src/lib.rs, pallets/circuit/src/lib.rs, pallets/circuit/src/machine/test.rs, pallets/circuit/src/square_up/mod.rs, pallets/circuit/vacuum/Cargo.toml, pallets/circuit/vacuum/src/lib.rs, pallets/xdns/src/lib.rs, pallets/xdns/src/tests.rs, primitives/src/circuit/traits.rs, primitives/src/circuit/types.rs, runtime/mini-mock/Cargo.toml, runtime/mini-mock/src/lib.rs, runtime/mock/src/lib.rs, types/abi/src/standard.rs, types/abi/src/to_abi.rs
Release Notes:
- New Feature: Added a new pallet called "Vacuum" with an `order` function for converting SFX actions into side effects and triggering an extrinsic on the circuit submit API.
- Bug fix: Modified error codes in multiple places within the `machine` module of the `circuit` pallet.
- Refactor: Added a new trait `CircuitSubmitAPI` and implemented it for the `Pallet` struct in the `circuit` crate.
- Test: Added a test module for the …
=> feat: add vacuum pallet with convert trait between Orders and SFX

runtime/standalone/src/system_config.rs, runtime/t0rn-parachain/src/system_config.rs
BaseCallFilter allows most of the calls (unknown ones too)
Release Notes:
- Bug fix: Modified the logic and functionality of the `BaseCallFilter` implementation in `system_config.rs` to allow all calls except for a few specific ones. The changes consolidate the checks for bridge methods into a single condition.
- Refactor: Commented out several lines of code that filtered specific calls, replacing them with a catch-all case to allow all calls to pass through. This …
=> fix: filter modification

pallets/attesters/src/lib.rs
Release Notes:
- New Feature: Introduced a new storage item `NextCommittee` and modified the function `get_current_committee_transition_for_target`.
- Bug fix: Fixed issues in the function `shuffle_committee` and removed attestations for a target.
- Refactor: Updated the current and previous committees.
- Test: Made changes to the test code.
> "Committees shuffled,
> Attestations removed,
> Bugs fixed, tests passed.
> A new feature emerged,
> With updated storage,
> The code evolves."
Release Notes:
- New Feature: Introduced a new storage item `NextCommittee` and modified the function `get_current_committee_transition_for_target`.
- Bug fix: Fixed issues in the function `shuffle_committee` and removed attestations for a target.
- Refactor: Updated the current and previous committees.
- …
=> fix: current committee transitions to next committee correctly

.github/workflows/github-pr-assignee.yml, .github/workflows/github-pr-project.yml
Release Notes:
- New Feature: Added GitHub Actions workflows to automatically assign pull request creators as assignees and add pull requests to project boards.
- Security: Improved security by suggesting the use of GitHub Secrets to store and retrieve tokens securely.
- Error Handling: Added error handling and logging for API requests.
- Performance: Optimized API requests to reduce the number of calls and combined related actions into a single request.
- Maintainability: Replaced hardcoded URLs with variables/constants for better maintainability.
> "Code dances with automation,
> Assigning tasks with dedication.
> Errors handled, security tight,
> Performance optimized, code takes flight.
> Maintained with care, logic refined,
> This PR brings enhancements, peace of mind."
=> ci(github): automate prs asignee and add to project

client/packages/cli/.gitignore, client/packages/cli/package.json, client/packages/cli/pnpm-lock.yaml, client/packages/cli/src/consts.ts, client/packages/cli/src/templates/transfer.ts, client/packages/cli/src/utils/circuit.ts
Release Notes:
- New Feature: Introduced environment variable usage for various parameters in the `sideEffects` object. The values of these parameters are now fetched from environment variables instead of being hard-coded.
- New Feature: Updated the code to use environment variables for SFX transaction parameters.
- Refactor: Added an import statement to import the `getConfig` function from a local file and used it to retrieve the `config.circuit.ws` value. Also added a console log statement.
- Chore: Renamed the file `.t3rnrc.json` to `config.json` without modifying the logic or functionality of the code.
- Refactor: Changed the value of `CONFIG_FILE` from ".t3rnrc.json" to "config.json".
> "Code evolves, variables dance,
> Environment brings a new chance.
> Configurations now flex their …
=> feat(cli): parametrize CLI with env variables

.github/workflows/executor.yml, client/packages/cli/helm/values-t0rn.yaml, client/packages/cli/src/commands/register/gateway.ts, client/packages/executor/config/config.ts, client/packages/executor/package.json, client/packages/executor/src/attestationManager/index.ts, client/packages/executor/src/circuit/listener.ts, client/packages/executor/src/circuit/relayer.ts, client/packages/executor/src/executionManager/execution.ts, client/packages/executor/src/executionManager/index.ts, client/packages/executor/src/executionManager/sideEffect.ts, client/packages/executor/src/gateways/substrate/relayer.ts, client/packages/executor/src/main.ts, client/packages/executor/src/pricing/coingecko.ts, client/packages/executor/src/prometheus.ts, pallets/attesters/contracts/scripts/deploy.js
Release Notes:
- Bug fix: Updated command in workflow to run `pnpm run fmt:check`.
- Configuration change: Modified `attestationVerifierAddress` value in Ethereum configuration.
- Refactor: Made changes to the constructor, method calls, variable assignments, and error handling in `AttestationManager` class.
- Enhancement: Modified logging statement in `CircuitListener` class to include additional information.
- Formatting: Fixed formatting issue by adding a space in `logger.error` statement in `CircuitRelayer` class.
- Typo fix: Removed extra space in log message in `execution.ts`.
- Logging improvement: Replaced `logger.info` calls with `logger.info({...}, ...)` in `index.ts`.
- Logging changes: Made changes to logging statements in `sideEffect.ts` and `coingecko.ts`.
- Error handling: …
=> fix: executor sending Confirmed Batches

Cargo.lock, pallets/portal/src/lib.rs, pallets/portal/src/tests.rs, pallets/xdns/src/lib.rs, pallets/xdns/src/tests.rs, primitives/src/lib.rs, runtime/common-pallets/Cargo.toml, runtime/common-pallets/src/lib.rs, runtime/mini-mock/Cargo.toml, runtime/mini-mock/src/lib.rs, runtime/mock/src/circuit_config.rs, runtime/mock/src/lib.rs, runtime/standalone/Cargo.toml, runtime/standalone/src/circuit_config.rs, runtime/standalone/src/lib.rs, runtime/t0rn-parachain/Cargo.toml, runtime/t0rn-parachain/src/circuit_config.rs, runtime/t0rn-parachain/src/lib.rs
- Added support for two new gateway vendors, Sepolia and XBI.
- Extended the `GatewayVendor` enum with `XBI` and `Sepolia`.
- Introduced a new error variant `LightClientNotFoundByVendor` to the `PortalError` enum.
- Implemented necessary configurations for the new `pallet_sepolia_finality_verifier` module.
> 🎉 Two new gateways join our band, 🚀
> Sepolia and XBI, hand in hand. 🤝
> With new errors to understand, 🧐
> And Sepolia's pallet on demand. 📦
> Our network grows across the land! 🌍🎉
=> feat: extend GatewayVendor select with XBI and Sepolia

client/packages/sdk/package.json, client/packages/sdk/src/price-estimation/__tests__/eth.test.ts, client/packages/sdk/src/price-estimation/eth.ts, client/packages/sdk/src/price-estimation/index.ts, client/packages/sdk/yarn.lock
**New Feature:**
- Added functionality for estimating gas fees for Ethereum transactions and EVM calls.
- Introduced new functions `estimateEvmCallGas`, `getTargetRpcEndpoint`, `EstimateEvmCallGasParams`, and `estimateActionGasFee`.
- Modified existing functions `getGasPrice` and `mapSfxActionToEthAction` to support the new feature.
- Added test cases for verifying the gas fee estimates for ETH transfer and EVM call actions.
> 🎉 With each line of code, we tread,
> On Ethereum's path, we now thread.
> Estimating gas, a feature so new,
> For EVM calls and transfers too! 🚀
=> feat: implement evm call price estimation

client/packages/cli/helm/templates/cronjob.yaml, client/packages/cli/helm/values-t0rn.yaml, client/packages/cli/src/utils/circuit.ts, client/packages/executor/config/config.ts, client/packages/executor/helm/templates/deployment.yaml, client/packages/executor/src/executionManager/index.ts, client/packages/executor/src/gateways/substrate/relayer.ts, client/packages/executor/src/index.ts, client/packages/executor/src/prometheus.ts
- Introduced environment variable `CIRCUIT_SIGNER_KEY` for signer key configuration, enhancing security.
- Added `accountPrefix` property to the `Gateway` and `Circuit` types for better account management.
- Replaced logger parameter with `prometheus` in `relayer.setup()` method call for improved metrics tracking.
- Implemented balance tracking for relayer and circuit signer with Prometheus metrics.
**Refactor:**
- Updated `SubstrateRelayer` class to use `prometheus` instead of `logger`.
- Modified balance retrieval methods and added new metrics for executor balance.
> 🎉 With keys secured and accounts prefixed right,  
> Our code now shines in a whole new light.  
> Balance tracked, metrics on sight,  
> Refactored code takes its flight! 🚀
=> fix(executor): custom signer for relaychain

client/packages/attester/package.json, client/packages/cli/package.json, client/packages/executor/package.json, client/packages/types/package.json, docs/main/package.json, pallets/attesters/contracts/package.json, scripts/upgrade-runtime-set-code.sh, types/abi/src/test_rlp_contracts/package.json
Fixes this strange yarn error which breaks our CI
=> ci: npx failures during ci

.github/workflows/auto-review.yml, .github/workflows/auto-summary.yml
This PR was reverted during zombienet failure so I recreated it.
=> ci: run auto gpt actions more sporadically

.github/workflows/attester.yml, .github/workflows/auto-review.yml, .github/workflows/auto-summary.yml, .github/workflows/cli.yml, .github/workflows/executor.yml, .github/workflows/grandpa-ranger.yml, client/packages/cli/helm/values-t0rn.yaml, client/packages/executor/helm/templates/deployment.yaml, client/packages/executor/helm/values.yaml, client/packages/executor/src/attestationManager/index.ts, client/packages/executor/src/circuit/listener.ts, client/packages/executor/src/circuit/relayer.ts, client/packages/executor/src/executionManager/index.ts, client/packages/executor/src/gateways/substrate/relayer.ts, client/packages/executor/src/prometheus.ts
**Debugging Enhancement:**
- Added debug logs in `relayer.ts` for inclusion proof and generating header inclusion proof using `Substrate.getStorageProof()`.
- Enhanced logging in `executionManager/index.ts` to provide detailed information about the execution confirmation queue, including vendor, queued blocks, batch blocks, ready height, and block height.
> 🎉 Debugging now a breeze, with logs that aim to please,
> Inclusion proofs and queues, no more confusion or misuse.
> With each line of code we commit, our software becomes more fit! 💪🚀
=> chore: add debug logs for inclusion proof

client/packages/executor/src/executionManager/index.ts, client/packages/executor/src/gateways/substrate/relayer.ts, client/packages/executor/src/index.ts, client/packages/executor/src/prometheus.ts, client/packages/executor/src/utils/index.ts
**New Feature**
- Removed `executorBids` counter metric from the `Prometheus` class.
- Introduced a new metric, `gateway_height`, to the `Prometheus` class for tracking the height of a gateway.
- Updated the `prometheus.gatewayHeight` metric with vendor and height information in `executionManager`.
- Added a new metric for gateway height in the `SubstrateRelayer` class.
- Incremented a Prometheus counter to track executor execution completion.
> 🎉 With metrics refined, our path is aligned,
> Gateway's height we now can find. 
> No more blind, in data we bind,
> To the rhythm of code, our minds are signed. 🚀
=> fix(executor): balance calculation and new metrics

client/packages/cli/src/commands/register/gateway.ts
**Refactor:**
- Fixed function signature in `handleRegisterGateway` by adding a missing comma.
- Improved code formatting in `registerGateway` and `handleRegisterGateway` functions.
> 🎉 Code's refined, no more dismay,  
> A missing comma found its way.  
> Formatting neat, as clear as day,  
> On the path of clean code, we stay! 🚀
=> fix: cli register gateway

client/packages/executor/src/executionManager/index.ts
```
- Enhanced error handling in `ExecutionManager` class by adding existence checks before accessing properties. This prevents potential crashes and improves system stability.
- Improved logging by adding warning logs when certain conditions are not met, aiding in easier debugging and issue resolution.
> 🎉 With each bug we lay to rest,  
> Our code becomes the very best.  
> No more crashes, no more fear,  
> For robust checks are now here! 🥳
```
=> fix: sfx in xtx existence check

node/standalone/src/rpc.rs, runtime/standalone/src/impl_versioned_runtime_with_api.rs
```
**New Feature**
- Added standalone RPC servers for the `Portal` and `Xdns` pallets.
- Integrated new RPC servers into the existing RPC module.
- Implemented runtime APIs for XDNS and Portal in the standalone runtime.
- Defined functions to fetch gateway records and heights.
> 🎉 With servers anew, for Portal and Xdns too,
> Merged into one, our RPC module's run.
> Runtime APIs, now shine under the sun,
> Fetching records and heights, oh what a view! 🚀
```
=> chore: reinstantiate standalone RPC for Portal + XDNS

.github/workflows/cli.yml
**Chore:**
- Added a new event trigger for the CLI workflow on the `development` branch in `.github/workflows/cli.yml`.
> 🎉 A change, small but mighty, we cheer,
> In our workflow, a new trigger appears.
> On `development`, it stands tall,
> Ready to respond to every call. 🚀
=> fix: gha for cli

Cargo.lock, Cargo.toml, runtime/common-types/Cargo.toml, runtime/common-types/src/lib.rs, runtime/t0rn-parachain/Cargo.toml, runtime/t0rn-parachain/src/xbi_config.rs
```
**New Feature**
- Added new constants `AssetHubLocationROC` and `AssetHubLocationUSDT` of type `MultiLocation`.
- Updated XCM configuration to accommodate the new asset locations.
> A toast to our code, it's a sight to behold 🥂,
> With new assets in place, we're breaking the mold.
> ROC and USDT, now part of our fold 🚀,
> In the realm of XCM, we're striking gold! 💰
```
=> feat: t0rn XCM config update

client/packages/grandpa-ranger/src/connection.ts, client/packages/grandpa-ranger/src/index.ts, client/packages/grandpa-ranger/src/prometheus.ts
```
**Refactor:**
- Removed `circuitActive` and `targetActive` properties from the `Prometheus` class in `prometheus.ts`, replaced with a single `heightDiff` property.
- Updated response status code based on the value of `heightDiff`.
- Modified `submitToCircuit` method in the `GrandpaRanger` class in `index.ts`, introducing two new private methods, `createTxBatch` and `createTx`, for handling batch and single transactions respectively.
> 🎉 With each refactor, we grow,
> Code now simpler, as we sow.
> Height difference takes the stage,
> In Grandpa Ranger's enlightened age.
> Transactions handled with more grace,
> As we continue our open-source race. 🚀
```
=> fix: grandpa-ranger should not escape submission loop

client/packages/sdk/package.json, client/packages/sdk/src/config/types.json, client/packages/sdk/src/gateways/gateway.ts, client/packages/sdk/src/index.ts, client/packages/sdk/src/utils/substrate.ts
```
**Refactor:**
- Modified the `getType` function in the `Gateway` class to simplify the vendor check.
- Added a new utility function `getStorage` for retrieving storage data from the Ethereum blockchain.
**Style:**
- Minor changes to import statements, constructor parameters, and formatting in `index.ts`.
```
> Here's to the code that's ever so bright, 🌟
> Simplifying checks, making it light. 💡
> With Ethereum storage now in sight, 👀
> Our SDK takes an impressive flight! 🚀
=> feat: sdk align for ethereum ranger

Cargo.lock, runtime/common-pallets/Cargo.toml, runtime/mini-mock/Cargo.toml, runtime/standalone/Cargo.toml, runtime/t0rn-parachain/Cargo.toml, runtime/t1rn-parachain/Cargo.toml
Chore: upgrade the sepolia eth pallet version
=> chore: upgrade sepolia pallet version

pallets/rewards/src/lib.rs, runtime/t0rn-parachain/src/hooks.rs
**New Feature:**
- Added a new function `find_inactive_authors` in the `pallet` module to filter out inactive authors based on the current session validators.
- Introduced a new block number constant `SESSION_PERIOD` in the `hooks` module, representing a 6-hour session period.
- Implemented logic to disable inactive validators from the session if they haven't produced any blocks during the session period.
> 🎉 With each passing block, we keep track,
> Of validators who do their part or slack.
> Inactive ones, we now can find,
> Ensuring our chain's health, aligned. 🚀
=> chore: disable inactive t0rn collators once per 6h session

pallets/circuit/src/lib.rs, pallets/circuit/src/tests.rs, pallets/circuit/vacuum/src/lib.rs, pallets/rewards/src/lib.rs, primitives/src/circuit/types.rs
- Added a complete vacuum trip functionality in the circuit pallet.
- Introduced a new test case and modifications to existing tests for enhanced coverage.
**Bug Fixes:**
- Fixed an issue where past accumulated settlements were being included in the current round calculation in the rewards pallet.
**Refactor:**
- Refactored the code for processing claims and accumulated settlements, including filtering based on roles and updating total claimed assets.
> 🎉 With bugs squashed and features anew, 🐞🔨
> Our code now sings a tune that's true. 🎶💻
> Tests refined, and logic too, 🧪🧠
> A release that makes our mission come through! 🚀✨
=> fix: disregard past accumulated settlements from current round calculation

Cargo.lock, Cargo.toml, runtime/t0rn-parachain/Cargo.toml, runtime/t0rn-parachain/src/xbi_config.rs, tests/zombienet/zombienet-xcm.toml, tests/zombienet/zombienet.sh
**New Feature:**
- Updated XCM configuration in `xbi_config.rs` for enhanced interoperability.
- Enabled dev accounts on AssetHub, providing developers with more flexibility and control.
- Improved Zombienet setup in `zombienet.sh`, enhancing the testing environment.
- Added calls to `build_polkadot`, `build_asset_hub`, and `build_collator` functions in the `spawn()` function, streamlining the process of spawning the zombienet.
> 🎉 With configs anew, and dev accounts too,  
> The chains interlink, in a networked zoo.  
> Zombienet spawns, with a build so fine,  
> In this world of code, your light will shine! 🚀
=> feat: updated XCM configuration including Zombienet setup with enabled dev accounts on AssetHub

client/packages/cli/package.json, client/packages/cli/pnpm-lock.yaml
=> fix: bump outdated t3rn SDK version at CLI package.json

Cargo.lock, runtime/common-pallets/Cargo.toml, runtime/mini-mock/Cargo.toml, runtime/standalone/Cargo.toml, runtime/t0rn-parachain/Cargo.toml, runtime/t1rn-parachain/Cargo.toml
Bump patch version for eth2-LC sepolia pallet
=> chore: upgrade eth2-lc for sepolia to next version

node/t2rn-parachain/src/chain_spec.rs, pallets/3vm/ethereum/src/tests/eip1559.rs, pallets/3vm/ethereum/src/tests/eip2930.rs, pallets/3vm/ethereum/src/tests/legacy.rs, pallets/evm/src/lib.rs, pallets/evm/src/runner/stack.rs, pallets/evm/src/tests.rs, primitives/src/threevm.rs, runtime/t0rn-parachain/src/contracts_config.rs, runtime/t1rn-parachain/src/contracts_config.rs, runtime/t2rn-parachain/src/circuit_config.rs, runtime/t2rn-parachain/src/contracts_config.rs, runtime/t2rn-parachain/src/treasuries_config.rs
=> fix: re-enable EVM decimals  conversion

docs/main/docs/executor/become-an-executor/binary-setup.md
Added export RPC_ENDPOINTS_L1RN='https://brn.rpc.caldera.xyz/' to Binary setup in Network & RPC section.
=> Added BRN RPC in the Network & RPC
